<?php

// $configData = Mage::getConfig()->getNode('default/import_export')->asArray();

$installer = $this;
$installer->startSetup();

$query = <<< EOF
INSERT INTO {$this->getTable('dataflow_profile')} (`profile_id`, `name`, `created_at`, `updated_at`, `actions_xml`, `gui_data`, `direction`, `entity_type`, `store_id`, `data_transfer`) VALUES (NULL, 'Categorie import (import_categories.csv)', '2010-08-17 08:51:48', '2010-08-17 08:58:11', '<action type="dataflow/convert_adapter_io" method="load">\r\n    <var name="type">file</var>\r\n    <var name="path">var/import</var>\r\n    <var name="filename"><![CDATA[import_categories.csv]]></var>\r\n    <var name="format"><![CDATA[csv]]></var>\r\n</action>\r\n<action type="dataflow/convert_parser_csv" method="parse">\r\n    <var name="delimiter"><![CDATA[,]]></var>\r\n    <var name="enclose"><![CDATA["]]></var>\r\n    <var name="fieldnames">true</var>\r\n    <var name="store"><![CDATA[0]]></var>\r\n    <var name="number_of_records">1</var>\r\n    <var name="decimal_separator"><![CDATA[.]]></var>\r\n    <var name="adapter">techtwo_ie/convert_adapter_categoryimport</var>\r\n    <var name="method">parse</var>\r\n</action>', '', NULL, '', 0, NULL);

INSERT INTO {$this->getTable('dataflow_profile')} (`profile_id`, `name`, `created_at`, `updated_at`, `actions_xml`, `gui_data`, `direction`, `entity_type`, `store_id`, `data_transfer`) VALUES (NULL, 'Categorie export (export_categories.csv)', '2010-08-17 08:52:13', '2010-08-17 08:57:48', '<action type="techtwo_ie/convert_parser_categoryexport" method="unparse">\r\n    <var name="store"><![CDATA[0]]></var>\r\n</action>\r\n\r\n<action type="dataflow/convert_mapper_column" method="map">\r\n</action>\r\n\r\n<action type="dataflow/convert_parser_csv" method="unparse">\r\n    <var name="delimiter"><![CDATA[,]]></var>\r\n    <var name="enclose"><![CDATA["]]></var>\r\n    <var name="fieldnames">true</var>\r\n</action>\r\n\r\n<action type="dataflow/convert_adapter_io" method="save">\r\n    <var name="type">file</var>\r\n    <var name="path">var/export</var>\r\n    <var name="filename"><![CDATA[export_categories.csv]]></var>\r\n</action>', '', NULL, '', 0, NULL);

INSERT INTO {$this->getTable('dataflow_profile')} (`profile_id`, `name`, `created_at`, `updated_at`, `actions_xml`, `gui_data`, `direction`, `entity_type`, `store_id`, `data_transfer`) VALUES (NULL, 'Product attributes import (import_bulk_product_attributes.csv)', '2010-08-17 08:53:19', '2010-08-17 09:14:28', '<action type="dataflow/convert_adapter_io" method="load">\r\n    <var name="type">file</var>\r\n    <var name="path">var/import</var>\r\n    <var name="filename"><![CDATA[import_bulk_product_attributes.csv]]></var>\r\n    <var name="format"><![CDATA[csv]]></var>\r\n</action>\r\n\r\n<action type="dataflow/convert_parser_csv" method="parse">\r\n    <var name="delimiter"><![CDATA[,]]></var>\r\n    <var name="enclose"><![CDATA["]]></var>\r\n    <var name="fieldnames">true</var>\r\n    <var name="store"><![CDATA[0]]></var>\r\n    <var name="number_of_records">1</var>\r\n    <var name="decimal_separator"><![CDATA[.]]></var>\r\n    <var name="adapter">techtwo_ie/convert_adapter_ProductAttributesimport</var>\r\n    <var name="method">parse</var>\r\n</action>', '', NULL, '', 0, NULL);

INSERT INTO {$this->getTable('dataflow_profile')} (`profile_id`, `name`, `created_at`, `updated_at`, `actions_xml`, `gui_data`, `direction`, `entity_type`, `store_id`, `data_transfer`) VALUES (NULL, 'Product attributes export (export_product_attributes.csv)', '2010-08-17 08:54:14', '2010-08-17 08:56:58', '<action type="techtwo_ie/convert_parser_ProductAttributesexport" method="unparse">\r\n    <var name="store"><![CDATA[0]]></var>\r\n    <var name="entitytypeid"><![CDATA[10]]></var>\r\n    <var name="recordlimit"><![CDATA[10]]></var>\r\n</action>\r\n\r\n<action type="dataflow/convert_mapper_column" method="map">\r\n</action>\r\n\r\n<action type="dataflow/convert_parser_csv" method="unparse">\r\n    <var name="delimiter"><![CDATA[,]]></var>\r\n    <var name="enclose"><![CDATA["]]></var>\r\n    <var name="fieldnames">true</var>\r\n</action>\r\n\r\n<action type="dataflow/convert_adapter_io" method="save">\r\n    <var name="type">file</var>\r\n    <var name="path">var/export</var>\r\n    <var name="filename"><![CDATA[export_product_attributes.csv]]></var>\r\n</action>', '', NULL, '', 0, NULL);

INSERT INTO {$this->getTable('dataflow_profile')} (`profile_id`, `name`, `created_at`, `updated_at`, `actions_xml`, `gui_data`, `direction`, `entity_type`, `store_id`, `data_transfer`) VALUES (NULL, 'Product import (import_all_products.csv)', '2010-08-17 08:55:31', '2010-08-17 09:14:02', '<action type="dataflow/convert_adapter_io" method="load">\r\n    <var name="type">file</var>\r\n    <var name="path">var/import</var>\r\n    <var name="filename"><![CDATA[import_all_products.csv]]></var>\r\n    <var name="format"><![CDATA[csv]]></var>\r\n</action>\r\n\r\n<action type="dataflow/convert_parser_csv" method="parse">\r\n    <var name="delimiter"><![CDATA[,]]></var>\r\n    <var name="enclose"><![CDATA["]]></var>\r\n    <var name="fieldnames">true</var>\r\n    <var name="store"><![CDATA[0]]></var>\r\n    <var name="number_of_records">1</var>\r\n    <var name="decimal_separator"><![CDATA[.]]></var>\r\n    <var name="adapter">techtwo_ie/convert_adapter_productimport</var>\r\n    <var name="method">parse</var>\r\n</action>', '', NULL, '', 0, NULL);

INSERT INTO {$this->getTable('dataflow_profile')} (`profile_id`, `name`, `created_at`, `updated_at`, `actions_xml`, `gui_data`, `direction`, `entity_type`, `store_id`, `data_transfer`) VALUES (NULL, 'Product export (export_products.csv)', '2010-08-17 08:56:11', '2010-08-17 08:56:11', '<action type="techtwo_ie/convert_adapter_productimport" method="load">\r\n    <var name="store"><![CDATA[0]]></var>\r\n    <var name="filter/adressType"><![CDATA[default_billing]]></var>\r\n</action>\r\n\r\n<action type="techtwo_ie/convert_parser_productexport" method="unparse">\r\n    <var name="store"><![CDATA[0]]></var>\r\n</action>\r\n\r\n<action type="dataflow/convert_mapper_column" method="map">\r\n</action>\r\n\r\n<action type="dataflow/convert_parser_csv" method="unparse">\r\n    <var name="delimiter"><![CDATA[,]]></var>\r\n    <var name="enclose"><![CDATA["]]></var>\r\n    <var name="fieldnames">true</var>\r\n</action>\r\n\r\n<action type="dataflow/convert_adapter_io" method="save">\r\n    <var name="type">file</var>\r\n    <var name="path">var/export</var>\r\n    <var name="filename"><![CDATA[export_products.csv]]></var>\r\n</action>', NULL, NULL, '', 0, NULL);
EOF;
$installer->run($query);

$installer->endSetup();