<div class="block block-login details" id="fixed_dropdown">
	<span></span>
    <div class="block-title">
        <strong><span><?php echo $this->__('Login') ?></span></strong>
		<a href="<?php echo $this->getUrl('customer/account/create',array('_secure'=>true)); ?>" class="regascus" title="<?php echo $this->__('Register as Customer') ?>"><?php echo $this->__('Register as Customer') ?></a>
    </div>
    <form action="<?php echo $this->getUrl('customer/account/loginPost',array('_secure'=>true)) ?>" method="post">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="block-content">
            <label for="mini-login"><?php echo $this->__('Email Address:') ?></label>
			<input type="text" name="login[username]" id="mini-login" class="input-text" placeholder="<?php echo $this->__('Email Address...') ?>"/>
            <label for="mini-password"><?php echo $this->__('Password:') ?></label>
			<input type="password" name="login[password]" id="mini-password" class="input-text" placeholder="<?php echo $this->__('Password') ?>" />
            <div class="actions">
                <button type="submit" class="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
            </div>
        </div>
    </form>
</div>