<div class="block block-login details dropdown">
	<span></span>
    <div class="block-title">
        <h3><?php echo $this->__('Login') ?></h3>
		<a href="<?php echo $this->getUrl('customer/account/create',array('_secure'=>true)); ?>" class="regascus" title="<?php echo $this->__('Register as Customer') ?>"><?php echo $this->__('Register as Customer') ?></a>
    </div>
    <form action="<?php echo $this->getUrl('customer/account/loginPost',array('_secure'=>true)) ?>" method="post" id="mini-login-form">
        <?php echo $this->getBlockHtml('formkey'); ?>
        <div class="block-content">
            <div class="input-box">
    			<input type="text" name="login[username]" class="input-text required-entry validate-email" placeholder="<?php echo $this->__('Email Address...') ?>" onfocus="this.placeholder = '';" onblur="this.placeholder = '<?php echo $this->__('Email Address...') ?>'; "/>
            </div>
            <div class="input-box">
    			<input type="password" name="login[password]" class="input-text required-entry validate-password" placeholder="<?php echo $this->__('Password') ?>" onfocus="this.placeholder = '';" onblur="this.placeholder = '<?php echo $this->__('Password') ?>'; " />
            </div>
            <div class="actions">
                <button type="submit" class="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
            </div>
            <a href="<?php echo Mage::getBlockSingleton('customer/form_login')->getForgotPasswordUrl() ?>" class="forgot-password" id="forgot-password"><?php echo $this->__('Forgot Your Password?') ?></a>
        </div>
    </form>
</div>
 <script type="text/javascript">
        //<![CDATA[
        var dataForm = new VarienForm('mini-login-form');
        //]]>
    </script>