<?php /*
$isLoggedin = Mage::getSingleton('customer/session')->isLoggedIn();
 
if ($isLoggedin) : ?>
	<div class="loyalty-program-container loggedin">
		<a href='#' data-lion-account-link="earn"><?php echo $this->__('Gyzs Credits') ?><span data-lion-points></span></a>
	</div>
<?php else: ?>
	<div class="loyalty-program-container">
		<a href='#' data-lion-account-link><?php echo $this->__('Gyzs Credits') ?></a>
	</div>
<?php endif; */?>