<?php
/**
 * @var Scommerce_GDPR_Block_Cookienotice $this
 */
?>

<style>
    .scommerce-gdpr-cookienotice {
        background: #<?php echo $this->getCookieBackgroundColor() ?>;
        color: #<?php echo $this->getCookieTextColor() ?>;
        padding: 5px 0;
    }
    .scommerce-gdpr-cookienotice .message {
        max-width: 960px;
        margin: 0 auto;
        text-align: center;
    }
    .scommerce-gdpr-cookienotice .message span.cookie-title {
        display: block;
        color: #<?php echo $this->getCookieTextColor() ?>;
        font-size: 16px;
        font-weight: bold;
        margin: 0.4em 0 0;
    }
    .scommerce-gdpr-cookienotice .message a {
        color: #<?php echo $this->getCookieLinkColor() ?>;
        text-decoration: underline;
    }
    .scommerce-gdpr-cookienotice .message a:hover {
        text-decoration: none;
    }
    .scommerce-gdpr-cookienotice .message .close a {
        font-size: 16px;
        text-decoration: none;
        font-weight: bold;
    }
    .scommerce-gdpr-cookienotice .message .close a:hover {
        text-decoration: underline;
    }
    .scommerce-gdpr-disabled {
        pointer-events: none;
        opacity: 0.4;
    }
	.bottom-position {
        position: fixed;
        width: 100%;
        z-index: 1000;
        bottom: 0;
        left: 0;
    }
</style>

<div id="js-cookienotice" class="scommerce-gdpr-cookienotice <?php echo (Mage::helper('scommerce_gdpr')->getCookieMessagePosition() == '2' ? "bottom-position" : "") ?>" style="display: none;">
    <div class="message">
        <span class="cookie-title"><?php echo $this->__('Cookie Policy');?></span>
        <p>
            <?php echo $this->getCookieTextMessage() ?><a href="<?php echo $this->getCmsPageUrl() ?>"><?php echo $this->getCookieLinkText() ?></a>
        </p>
        <p class="accept">
            <a id="js-gdpr-accept" href=""><?php echo $this->__('Accept');?></a>
        </p>
        <?php if (! $this->isBlocked()): ?>
            <p class="decline">
                <a id="js-gdpr-decline" href=""><?php echo $this->__('Decline');?></a>
            </p>
        <?php endif ?>
    </div>
</div>

<script>
    (function($) {
        $(function() {
            // Model
            var Model = {
                wrapper: $('<?php echo $this->getBlockIdorClass() ?>'), // Page wrapper for enable/disable access to page
                block: $('#js-cookienotice'), // Block with cookie alert text and links
                wrapperClass: 'scommerce-gdpr-disabled', // Css class for enabling/disabling page wrapper
                isBlocked: <?php echo (int) $this->isBlocked() ?>, // Config value for enable/disable accees to site page
                cookieKey: '<?php echo $this->getCookieKey() ?>', // Cookie key to check accepted cookie policy
				cookieClosedKey: '<?php echo $this->getCookieClosedKey() ?>', // Closed Cookie key to check if cookie message is closed

                // Initialize model
                initialize: function() {
                    if (! this.get(this.cookieClosedKey)) {
                        this.block.show();
                    }
                    if (this.isBlocked && ! this.get(this.cookieKey)) {
                        this.disable();
                    }
                },

                // Set cookie value
                set: function(name, value) {
                    Mage.Cookies.set(name, value, new Date(new Date().getTime() + (100 * 365 * 24 * 60 * 60)));
                },

                // Get cookie value (just check to value is 1)
                get: function(name) {
                    return Mage.Cookies.get(name) == 1;
                },

                // Close gdpr block
                close: function() {
                    this.set(this.cookieClosedKey, 1);
                    this.block.hide();
                },

                // Accept rules
                accept: function() {
                    this.close();
                    this.set(this.cookieKey, 1);
                    if (this.isBlocked) {
                        this.enable();
                    }
                },

                // Decline rules
                decline: function() {
                    this.close();
                    this.set(this.cookieKey, 0);
                },

                // Disable page wrapper ("close" access to site page)
                disable: function() {
                    this.wrapper.addClass(this.wrapperClass);
                },

                // Enable page wrapper ("allow" access to site page)
                enable: function() {
                    this.wrapper.removeClass(this.wrapperClass);
                }
            };

            // Callbacks
            $('#js-gdpr-accept').on('click', function(e) {
                e.preventDefault();
                Model.accept();
            });
            $('#js-gdpr-decline').on('click', function(e) {
                e.preventDefault();
                Model.decline();
            });

            // Initialize
            Model.initialize();
        });
    })(jQuery);
</script>
