<?php
ob_start();
/**
 * Bestsellers block
 * @see Queldorei_ShopperSettings_Block_Bestsellers
 */
$products = $this->getBestsellers();
if (count($products) > 0) :
    $helper = $this->helper('shoppersettings/image');
    $imgX = 180;
    $imgY = $helper->calculateHeight($imgX);
    $_helper = $this->helper('catalog/output');
	$_featuredHelper = Mage::helper('featured');
    ?>    
    <ul class="products-grid">
        <?php
        foreach ($products as $_product) :
            $productLabels = Mage::helper('featured')->getIsFeaturedProduct($_product);
            ?>
            <li class="item newsingle">
                <div class="item-inner">
                    <div class="regular">
                        <?php if ($_product->getFeatured()): ?>
                            <div class="featuredproducts bestseller">
                                <span style="background-color:#<?php echo trim($productLabels['labeldata']->getBgcolor()); ?>;color:#<?php echo trim($productLabels['labeldata']->getTextcolor()); ?>;border:2px solid #<?php echo trim($productLabels['labeldata']->getBghovercolor()); ?>"><?php echo $productLabels['labelvalue']; ?></span>
                            </div>
                            <div class="toshow">
                                <div class="featuredproducts-hover bestseller">
                                    <span style="background-color:#<?php echo trim($productLabels['labeldata']->getBghovercolor()); ?>;color:#<?php echo trim($productLabels['labeldata']->getTexthovercolor()); ?>;border:2px solid #<?php echo trim($productLabels['labeldata']->getBghovercolor()); ?>"><?php echo $productLabels['labelvalue']; ?></span>
                                </div>
                            </div>
                        <?php endif; ?>
                        <a href="<?php echo $_product->getProductUrl() ?>"
                           title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                            <img
                                src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX, $imgY) ?>"
                                data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX * 2, $imgY * 2) ?>"
                                width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>"
                                alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/>
                        </a>
                        <div class="product-info">
                            <div class="product-sku">
                                <?php
                                ?>
                                <?php echo Mage::helper('common')->getGYZSSku($_product->getSku()); ?>
                            </div>
                            <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                            <a class="product-name" href="<?php echo $_product->getProductUrl() ?>"
                               title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                            <div class="price-container">
                                <?php echo $this->getPriceHtml($_product, true) ?>
                                <?php if ($_product->getTypeId() != 'grouped'): ?>
                                    <div class="price-per-attr">
                                        <span> <?php echo $this->__('per') . " " . $_featuredHelper->getStockAndUnit($_product); ?></span>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                        <div class="category-url">
                            <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $this->__('View Product'); ?>"><?php echo $this->__('View Product'); ?></a>
                        </div>
                    </div>
                    <div class="toshow bottom">
                        <div class="hover_bottom">
                            <div class="extra-stock">
                                <div class="stock-limit">
                                    <?php if ((int) Mage::getConfig()->getNode('default/combipac')->enable_stock && !$_product->isGrouped()) : ?>
                                        <div class="checkstock list <?php echo $_product->getSku(); ?>" id="<?php echo $_product->getSku(); ?>">

                                        </div>
                                    <?php endif; ?>
                                </div>
                                <div class="action-container">
                                    <div class="qty-wrapper">
                                        <?php $unit = Mage::helper('featured')->getProductUnit($_product->getData('verkoopeenheid')); ?>
                                        <input type="text" name="qty" id="qty_<?php echo $_product->getSku(); ?>" min="1" maxlength="5" onkeypress="validateNumber(event)" value="1" title="<?php echo $this->__('Qty') ?>" class="input-text qty grid" />
                                        <input type="hidden" class="hiddenstock"
                                               id="stock_qty_<?php echo $_product->getSku(); ?>"
                                               title="<?php echo $_product->getSku(); ?>"/>
                                        <input type="hidden" class="hiddenstockstatus"
                                               id="stock_qty_status_<?php echo $_product->getSku(); ?>"
                                               value="<?php echo $_product->getArtikelstatus(); ?>"/>
                                        <input type="hidden" class="hiddenindealpacking"
                                               id="stock_qty_ideal_<?php echo $_product->getSku(); ?>"
                                               value="<?php echo $_product->getIdealeverpakking(); ?>"/>
                                        <input type="hidden" class="hiddenverkoopeenheid"
                                               id="stock_qty_verkoopeenheid_<?php echo $_product->getSku(); ?>"
                                               value="<?php echo $unit; ?>"/>
                                        <input type="hidden" class="hiddenafwijkenidealeverpakking"
                                               id="stock_qty_afwijkenidealeverpakking_<?php echo $_product->getSku(); ?>"
                                               value="<?php echo $_product->getAfwijkenidealeverpakking(); ?>"/>
                                        <input type="hidden" class="leverancier"
                                               id="leverancier_<?php echo $_product->getSku(); ?>"
                                               value="<?php echo $_product->getLeverancier(); ?>"/>
                                    </div>
                                    <div class="quantity-per-attr">
                                        <span id="stock-label-<?php echo $_product->getSku(); ?>" class="stock-label-<?php echo $_product->getSku(); ?>">
                                            <?php if (!(int) $_product->getData('afwijkenidealeverpakking')): ?>
                                                <?php $stockInfo = $_product->getData('idealeverpakking'); ?>
                                                <?php if ($stockInfo != '1'): ?>
                                                    <?php echo '&nbsp;x&nbsp;' . $stockInfo; ?>
                                                <?php endif; ?>
                                                <?php
                                            else :
                                                $stockInfo = 1;
                                                ?>
                                            <?php endif; ?>
                                            <?php echo Mage::helper('featured')->getStockUnit($stockInfo, $unit); ?>
                                        </span>
                                    </div>
                                    <div class="button-container">
                                        <button type="button"
                                                    title="<?php echo $this->__('Add to Cart') ?>"
                                                    id="cart_button_<?php echo $_product->getSku(); ?>"
                                                    class="button btn-cart ajax-cart"
                                                    data-url="<?php echo $this->getAddToCartUrl($_product); ?>"
                                                    data-id="<?php echo $_product->getId(); ?>">
                                                <?php echo $this->__('Add to Cart') ?>
                                            </button>
                                    </div>
                                </div>
                            </div>
                            <span class="ajax_loading" id='ajax_loading<?php echo $_product->getId() ?>'><img src='<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>' alt="Loading.."/></span>
                            <div class="view-product">
                                <a href="<?php echo $_product->getProductUrl(); ?>"
                                   title="<?php echo $this->__('View Product') ?>">
                                       <?php echo $this->__('View Product') ?>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
