<?php
/**
 * Brands slider template
 *
 * @see Queldorei_ShopperSettings_Block_Brands
 */
 
?>


<div class="block-blog">
<div class="row clearfix">
    <div class="block-title">
        <h1><?php echo $this->__('The Gyzs Blog') ?></h1>
    </div>
    <div class="block-content">
		<ul>        
			<li class="item first">
				<div class="regular">
					<a href="#"  class="product-image">
						<img src="<?php echo $this->getSkinUrl()?>images/blog1.png" alt="" />
					</a>
					<div class="blog-info" style="height: 99px;">
						<div class="blog-title">
							<span><?php echo $this->__('Job Tips') ?></span>
						</div>
						<a class="blog-short" href="#" title="<?php echo $this->__('Add punch Rose if you suffer from pests') ?>" ><?php echo $this->__('Add punch Rose if you suffer from pests') ?></a>                    
					</div>
				</div>
				<div class="category-url">
					<a title="<?php echo $this->__('Read more') ?>" href="#"><?php echo $this->__('Read more') ?></a>            
				</div>
			</li>
			<li class="item">
				<div class="regular">
					<a href="#"  class="product-image">
						<img src="<?php echo $this->getSkinUrl()?>images/blog2.png" alt="" />                
					</a>
					<div class="blog-info" style="height: 99px;">
						<div class="blog-title">
							<span><?php echo $this->__('Job Tips') ?></span>
						</div>
						<a class="blog-short" href="#" title="<?php echo $this->__('Add punch Rose if you suffer from pests') ?>" ><?php echo $this->__('Add punch Rose if you suffer from pests') ?></a>                    
					</div>
				</div>
				<div class="category-url">
					<a title="<?php echo $this->__('Read more') ?>" href="#"><?php echo $this->__('Read more') ?></a>
				</div>           
			</li>    	
			<li class="item">
				<div class="regular">
					<a href="#"  class="product-image">
						<img src="<?php echo $this->getSkinUrl()?>images/blog3.png" alt="" />                  
					</a>
					<div class="blog-info" style="height: 99px;">
						<div class="blog-title">
							<span><?php echo $this->__('Job Tips') ?></span>
						</div>
						<a class="blog-short" href="#" title="<?php echo $this->__('Klustip: wallpaper without bubbles') ?>"><?php echo $this->__('Klustip: wallpaper without bubbles') ?></a>                   
					</div>
				</div>
				<div class="category-url">
					<a title="<?php echo $this->__('Read more') ?>" href="#"><?php echo $this->__('Read more') ?></a>
				</div>
			</li>
			<li class="item">
				<div class="regular">
					<a href="#" class="product-image">
						<img src="<?php echo $this->getSkinUrl()?>images/blog4.png" alt="" />                            
					</a>
					<div class="blog-info" style="height: 99px;">
						<div class="blog-title">
							<span><?php echo $this->__('Job Tips') ?></span>
						</div>
						<a class="blog-short" href="#" title="<?php echo $this->__('Klustip: drill how does that work?') ?>"><?php echo $this->__('Klustip: drill how does that work?') ?></a>                    
					</div>              
				</div>
				<div class="category-url">
					<a href="#" title="<?php echo $this->__('Read more') ?>"><?php echo $this->__('Read more') ?></a>           
				</div>
			</li>    	
			<li class="item">
				<div class="regular">
					<a href="#" class="product-image">
						<img src="<?php echo $this->getSkinUrl()?>images/blog5.png" alt="" />   
					</a>
					<div class="blog-info" style="height: 99px;">
						<div class="blog-title">
							<span><?php echo $this->__('Job Tips') ?></span>
						</div>
						<a class="blog-short" href="#" title="<?php echo $this->__('How do you determine the direction of a door or') ?>"><?php echo $this->__('How do you determine the direction of a door or') ?></a>                    
					</div>
				</div>
			   <div class="category-url">            
					<a  href="#" title="<?php echo $this->__('Read more') ?>"><?php echo $this->__('Read more') ?></a>			</div>
			</li>
        </ul>
		<div class="read-more">
			<a title="<?php echo $this->__('Go to the blog of GYZS') ?>" href="#"><?php echo $this->__('Go to the blog of GYZS') ?></a>
		</div>
	</div>
</div>
</div>