<?php
/**
 * Brands slider template
 *
 * @see Queldorei_ShopperSettings_Block_Brands
 */
//$prod=new Mage_Catalog_Block_Product_View;
$helper = $this->helper('shoppersettings/image');
$imgX = 234;
$imgY = $helper->calculateHeight($imgX);
$_helper = $this->helper('catalog/output');
$products = Mage::getModel('catalog/category')->load($this->getData('category_id'))->getProductCollection();
$time = uniqid('shopper_');
$groupTypeId = Mage_Catalog_Model_Product_Link::LINK_TYPE_GROUPED;
$_featuredHelper = Mage::helper('featured');

if ($products->getSize() > 0) :
    ?>

    <!-- brands slider BOF -->

    <div class="product-slider-container special-slider  block block-bestsellers">
        <div class="row">
            <div class="clearfix title-container block-title">
                <h2><?php echo $this->__('specially selected for you') ?></h2>
                <!--<a href="#" class="jcarousel-prev-horizontal" id="special_carousel_prev<?php echo $time; ?>"></a>
                <a href="#" class="jcarousel-next-horizontal" id="special_carousel_next<?php echo $time; ?>"></a>-->
            </div>
            <div class="block-content">
                <ul id="special_carousel<?php echo $time; ?>" class="brands jcarousel-skin-tango clearfix products-grid">
                    <?php foreach ($products as $_product) :
                        $_product = Mage::getModel('catalog/product')->load($_product->getId());
                        ?>
                        <li class="item">
                            <div class="regular">
							<?php
									if ($_product->getTypeId() == 'grouped'): ?>
									<div class="regular-associatedproducts">
								<?php
									//$_associatedProducts = $_product->getTypeInstance(true)->getAssociatedProducts($_product);
									//$dispcount = count($_associatedProducts);
                                    $dispcount = $_featuredHelper->getAssociativeItemCount($_product);
                                ?>
									<?php echo $dispcount; ?>
									</div>
								<?php
									endif;
								?>
                                <a href="<?php echo $_product->getProductUrl() ?>"
                                   title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                                    <?php echo $this->helper('shoppersettings')->getLabel($_product); ?>
                                    <img
                                        src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX, $imgY) ?>"
                                        data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX * 2, $imgY * 2) ?>"
                                        width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>"
                                        alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/>
                                </a>

                                <div class="product-info">
                                    <div class="product-sku">
                                        <?php
                                        if ($_product->getTypeId() != 'grouped'):
                                            ?>
                                            <span><?php echo Mage::helper('common')->getGYZSSku($_product->getSku()); ?></span>
                                        <?php
                                        else:
                                            echo $this->__('Grouped Product');
                                        endif; ?>
                                    </div>
                                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                    <a class="product-name" href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>

                                    <div class="price-container">

										<?php echo $this->getPriceHtml($_product, true) ?>
                                        <?php if ($_product->getTypeId() != 'grouped'): ?>
                                            <div class="price-per-attr">
                                                <span><?php echo $this->__('per') . " " . $_featuredHelper->getStockAndUnit($_product); ?></span>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                                <div class="category-url">
                                    <?php if ($_product->getTypeId() != 'grouped'): ?>
                                        <a href="<?php echo $_product->getProductUrl(); ?>"
                                           title="<?php echo $this->__('View Product') ?>"><?php echo $this->__('View Product') ?></a>
                                    <?php else: ?>
                                        <a href="<?php echo $_product->getProductUrl(); ?>"
                                           title="<?php echo $this->__('View Variants') ?>"><?php echo $this->__('View Variants')." "."(".$dispcount.")";  ?></a>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="hover">
                                <?php if ($_product->getTypeId() != 'grouped'): ?>
                                    <div class="hover-compare">
                                        <input type="checkbox" class="checkbox">
                                        <span class="checkbox"></span>
                                        <a class="compare-link" href=""
                                           title="<?php echo $this->__('Compare') ?>"><?php echo $this->__('Compare') ?></a>
                                    </div>
                                <?php endif; ?>
								<?php
									if ($_product->getTypeId() == 'grouped'): ?>
									<div class="hover-associatedproducts">
								<?php
//									$_associatedProducts = $_product->getTypeInstance(true)->getAssociatedProducts($_product);
//									$dispcount = count($_associatedProducts);
                                $dispcount = $_featuredHelper->getAssociativeItemCount($_product);

                                ?>
									<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
										<span><?php echo $dispcount; ?></span>
										<i class="fi-list-bullet"></i>
									</a>
									</div>
								<?php
									endif;
								?>

                                <?php if (Mage::getStoreConfig('shoppersettings/ajax/cart')) : //quick view button ?>
                                    <a href='<?php echo $this->getUrl('ajax/index/options', array('product_id' => $_product->getId())); ?>'
                                       data-fancybox-group="gallery" class='fancybox quick-view'
                                       id='fancybox<?php echo $_product->getId() ?>'><?php echo $this->__('quick view') ?></a>
                                <?php endif; ?>
                                <a href="<?php echo $_product->getProductUrl() ?>"
                                   title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                                    <?php echo $this->helper('shoppersettings')->getLabel($_product); ?>
                                    <?php
                                    $_product->load('media_gallery');
                                    $back_img = $_product->getMediaGalleryImages()->getItemByColumnValue('label', 'back');
                                    if ($back_img) : ?>
                                        <img
                                            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $back_img->getFile())->resize($imgX, $imgY) ?>"
                                            data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image', $back_img->getFile())->resize($imgX * 2, $imgY * 2) ?>"
                                            width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>"
                                            alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/>
                                    <?php else : ?>
                                        <img
                                            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX, $imgY) ?>"
                                            data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX * 2, $imgY * 2) ?>"
                                            width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>"
                                            alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/>
                                    <?php endif; ?>
                                </a>

                                <div class="product-info">

                                    <div class="product-sku">
                                        <?php
                                        if ($_product->getTypeId() != 'grouped'):
                                            ?>
                                            <span><?php echo Mage::helper('common')->getGYZSSku($_product->getSku()); ?></span>
                                        <?php
                                        else:
                                            echo $this->__('Grouped Product');
                                        endif; ?>

                                    </div>

                                    <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>

                                    <a class="product-name" href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>
                                    <?php if ($_product->getRatingSummary()) {
                                        echo $this->getReviewsSummaryHtml($_product);
                                    } ?>
                                    <div class="price-container">
                                        <?php //echo $product_block->getPriceHtml($_product, true)
										echo Mage_Catalog_Block_Product::getPriceHtml($_product, true)
										?>
                                        <div class="price-per-attr">
                                            <?php
                                            if ($_product->getTypeId() != 'grouped'): ?>
                                                <div class="price-per-attr">
                                                    <span> <?php echo $this->__('Per') . " " . $prijsfactor . " " . $verkoopeenheid; ?></span>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                <span class="ajax_loading" id='ajax_loading<?php echo $_product->getId()?>'><img
                                        src='<?php echo $this->getSkinUrl('images/ajax-loader.gif')?>' alt="Loading.."/></span>
                                </div>
                                <div class="hover_bottom">
                                    <?php if ($_product->getTypeId() != 'grouped'): ?>
                                        <div class="extra-stock">
                                            <div class="stock-limit">
                                                <!--<span class="signal"></span>
                                        <span class="info">2.023 <?php /*echo $this->__('In stock') */
                                                ?></span>-->
                                                <?php if ((int)Mage::getConfig()->getNode('default/combipac')->enable_stock && !$_product->isGrouped()) : ?>
                                                    <div class="checkstock list" id="<?php echo $_product->getSku(); ?>">

                                                    </div>
                                                <?php endif; ?>
                                            </div>
                                            <div class="action-container">
                                                <div class="qty-wrapper">
                                                    <input type="text" name="qty" id="qty_<?php echo $_product->getSku(); ?>" min="1" maxlength="5" onkeypress="validateNumber(event)" value="1" title="<?php echo $this->__('Qty') ?>" class="input-text qty grid" />
                                                    <input type="hidden" class="hiddenstock"
                                                           id="stock_qty_<?php echo $_product->getSku(); ?>"
                                                           title="<?php echo $_product->getSku(); ?>"/>
                                                    <input type="hidden" class="hiddenstockstatus"
                                                           id="stock_qty_status_<?php echo $_product->getSku(); ?>"
                                                           value="<?php echo $_product->getArtikelstatus(); ?>"/>
                                                    <input type="hidden" class="hiddenindealpacking"
                                                           id="stock_qty_ideal_<?php echo $_product->getSku(); ?>"
                                                           value="<?php echo $_product->getIdealeverpakking(); ?>"/>
                                                    <input type="hidden" class="hiddenverkoopeenheid"
                                                           id="stock_qty_verkoopeenheid_<?php echo $_product->getSku(); ?>"
                                                           value="<?php echo $_product->getVerkoopeenheid(); ?>"/>
                                                    <input type="hidden" class="hiddenafwijkenidealeverpakking"
                                                           id="stock_qty_afwijkenidealeverpakking_<?php echo $_product->getSku(); ?>"
                                                           value="<?php echo $_product->getAfwijkenidealeverpakking(); ?>"/>
                                                    <input type="hidden" class="leverancier"
                                                           id="leverancier_<?php echo $_product->getSku(); ?>"
                                                           value="<?php echo $_product->getLeverancier(); ?>"/>
                                                </div>
                                                <div class="quantity-per-attr">
											<span>
                                                <?php if (!(int)$_product->getData('afwijkenidealeverpakking')): ?>
                                                    <?php echo '&nbsp;x&nbsp;' . $_product->getData('idealeverpakking');
                                                else :
                                                    echo "&nbsp;x&nbsp;1";
                                                    ?>
                                                <?php endif; ?>
                                                <?php echo $_product->getData('verkoopeenheid'); ?>
                                        </span></div>
                                                <div class="button-container">
                                                    <?php if ($_product->isSaleable()): ?>

                                                        <?php if (Mage::getStoreConfig('shoppersettings/ajax/cart')) : ?>

                                                            <?php if (!($_product->getTypeInstance(true)->hasRequiredOptions($_product) || $_product->isGrouped())) { ?>
                                                                <button type="button"
                                                                            title="<?php echo $this->__('Add to Cart') ?>"
                                                                            class="button btn-cart ajax-cart"
                                                                            id="cart_button_<?php echo $_product->getSku(); ?>"
                                                                            data-url="<?php echo $prod->getAddToCartUrl($_product); ?>"
                                                                            data-id="<?php echo $_product->getId(); ?>">
                                                                        <?php echo $this->__('Add to Cart') ?>
                                                                    </button>
                                                            <?php } else { ?>
                                                                <button type="button"
                                                                            title="<?php echo $this->__('Add to Cart') ?>"
                                                                            id="cart_button_<?php echo $_product->getSku(); ?>"
                                                                            class="button btn-cart show-options"
                                                                            data-id="<?php echo $_product->getId(); ?>">
                                                                        <?php echo $this->__('Add to Cart') ?>
                                                                    </button>
                                                            <?php } ?>

                                                        <?php else: ?>
                                                           <button type="button"
                                                                        title="<?php echo $this->__('Add to Cart') ?>"
                                                                        id="cart_button_<?php echo $_product->getSku(); ?>"
                                                                        class="button btn-cart"
                                                                        onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                                                    <?php echo $this->__('Add to Cart') ?>
                                                                </button>
                                                        <?php endif; ?>

                                                    <?php else: ?>
                                                        <p class="availability out-of-stock">
                                                            <span><?php echo $this->__('Out of stock') ?></span></p>
                                                    <?php endif; ?>
                                                </div>
                                            </div>
                                        </div>
                                    <?php endif; ?>
                                    <?php if ($_product->getTypeId() != 'grouped'): ?>
                                        <div class="view-product">

                                            <a href="<?php echo $_product->getProductUrl(); ?>"
                                               title="<?php echo $this->__('View Product') ?>"><?php echo $this->__('View Product') ?></a>
                                        </div>
                                    <?php else: ?>
                                        <div class="view-variants">
                                            <a href="<?php echo $_product->getProductUrl(); ?>"
                                               title="<?php echo $this->__('View Variants') ?>"><?php echo $this->__('View Variants')." "."(".$dispcount.")";  ?></a>

                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {

            var carouselID = '#special_carousel<?php echo $time; ?>';
            function mycarousel_initCallback(carousel) {
                $('#special_carousel_next<?php echo $time; ?>').bind('click', function () {
                    carousel.next();
                    return false;
                });
                $('#special_carousel_prev<?php echo $time; ?>').bind('click', function () {
                    carousel.prev();
                    return false;
                });
                if (typeof $('.product-slider-container').swipe !== 'undefined') {
                    $('.product-slider-container').swipe({
                        swipeLeft: function () {
                            carousel.next();
                        },
                        swipeRight: function () {
                            carousel.prev();
                        },
                        swipeMoving: function () {
                        }
                    });
                }
            };

            var mycarousel_reloadCallback = function (carousel) {
                if (!isResize('special_carousel_<?php echo $time; ?>')) return;
                carousel.list = $(carouselID);
                var li = $(carouselID).children('li');
                carousel.list.css(carousel.lt, "0px");
                carousel.list.css(carousel.wh, $(li.get(0)).outerWidth(!0) * li.size() + 100);
                carousel.first = 1;
                carousel.last = $(carouselID).parent().width() / $(li.get(0)).outerWidth(!0);

            }
        });
    </script>
    <!-- brands slider EOF -->
<?php endif; unset($prod); ?>
