<?php
/**
 * class        Hs_Transsmartadjustment_Model_Sales_Shipping_Shipping_Carrier_Tablerate
 * @category    Transsmart
 * @package     Hs_Transsmartadjustment
 * @author      Hs_SJD
 * @date        06 June, 2018
 *
 */
class Hs_Transsmartadjustment_Model_Sales_Shipping_Shipping_Carrier_Tablerate extends Transsmart_Shipping_Model_Shipping_Carrier_Tablerate
{
    public function collectRates(Mage_Shipping_Model_Rate_Request $request)
    {
        exit('in Hs_Transsmartadjustment: collectRates');
        parent::collectRates($request); // TODO: Change the autogenerated stub
    }
}