<?php

/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Kbase
 * @copyright  Copyright (c) 2008-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */

if(!AW_Kbase_Helper_Data::getFrontendEnabled()) return;
if(AW_Kbase_Helper_Data::isModuleOutputDisabled()) return;

?>
<div class="kbase-main-header-container">
<p><?php echo Mage::getStoreConfig('kbase/general/title') ?></p>
</div>
<div class="kbase-main-header">
	<div class="kbase-banner">
		<div class="service-container">
			<h1><?php echo $this->__('Service at GYZS') ?></h1>
			<h2><?php echo $this->__('Always answer') ?></h2>
			<h2><?php echo $this->__('to your question.') ?></h2>
		</div>
	</div>    
</div>