<?php
$collection = $this->getSaleProducts();
if (count($collection) > 0) :
    $catId = $this->getSaleCategoryId();
    $catUrl = $this->getSaleCategoryUrl();

    $helper = $this->helper('shoppersettings/image');
    $imgX = 234;
    $imgY = $helper->calculateHeight($imgX);
    $_helper = $this->helper('catalog/output');
	$_featuredHelper = Mage::helper('featured');

    $time = uniqid('shopper_');
    ?>
    <div class="product-slider-container special-slider  block block-bestsellers">
        <div class="row">
            <div class="clearfix title-container block-title">
                <h2><?php echo $this->__('specially selected for you') ?></h2>
                <!--<a href="#" class="jcarousel-prev-horizontal" id="special_carousel_prev<?php echo $time; ?>"></a>
                <a href="#" class="jcarousel-next-horizontal" id="special_carousel_next<?php echo $time; ?>"></a>-->
            </div>
            <div class="block-content">
                <ul id="special_carousel<?php echo $time; ?>"
                    class="brands jcarousel-skin-tango clearfix products-grid">
                        <?php
                        foreach ($collection as $_product) :
                            $productLabels = Mage::helper('featured')->getIsFeaturedProduct($_product);
                            if ($_product->getTypeId() == 'grouped') {
                                $_associatedProducts = $_product->getTypeInstance(true)->getAssociatedProducts($_product);
                                $dispcount = count($_associatedProducts);
                            }
                            ?>
                        <li class="item newsingle">
                            <div class="item-inner">
                                <div class="regular">
                                    <?php if ($_product->getTypeId() == 'grouped' && $dispcount > 0): ?>
                                        <div class="regular-associatedproducts associatedbox">
                                            <div>
                                                <span><?php echo $dispcount; ?></span>
                                                <i class="fa fa-list-ul"></i>
                                            </div>
                                        </div>
                                    <?php else: ?>
                                        <?php if ($_product->getFeatured()): ?>
                                            <div class="featuredproducts homespecial">
                                                <span style="background-color:#<?php echo trim($productLabels['labeldata']->getBgcolor()); ?>;color:#<?php echo trim($productLabels['labeldata']->getTextcolor()); ?>;border:2px solid #<?php echo trim($productLabels['labeldata']->getBghovercolor()); ?>"><?php echo $productLabels['labelvalue']; ?></span>
                                            </div>
                                            <div class="toshow">
                                                <div class="featuredproducts-hover homespecial">
                                                    <span style="background-color:#<?php echo trim($productLabels['labeldata']->getBghovercolor()); ?>;color:#<?php echo trim($productLabels['labeldata']->getTexthovercolor()); ?>;border:2px solid #<?php echo trim($productLabels['labeldata']->getBghovercolor()); ?>"><?php echo $productLabels['labelvalue']; ?></span>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                    <?php endif; ?>

                                    <a href="<?php echo $_product->getProductUrl() ?>"
                                       title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
                                        <img
                                            src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX, $imgY) ?>"
                                            data-srcX2="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgX * 2, $imgY * 2) ?>"
                                            width="<?php echo $imgX; ?>" height="<?php echo $imgY; ?>"
                                            alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/>
                                    </a>

                                    <div class="product-info">
                                        <div class="product-sku">
                                            <?php
                                            if ($_product->getTypeId() != 'grouped'):
                                                ?>
                                                <?php echo Mage::helper('common')->getGYZSSku($_product->getSku()); ?>
                                                <?php
                                            else:
                                                if ($dispcount > 0) {
                                                    echo $this->__('Product with') . " " . $dispcount . " " . $this->__('variants.');
                                                } else {
                                                    echo $this->__('Grouped Product');
                                                }
                                            endif;
                                            ?>
                                        </div>
                                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                                        <a class="product-name" href="<?php echo $_product->getProductUrl() ?>"
                                           title="<?php echo $_productNameStripped; ?>"><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?></a>

                                        <div class="price-container">
                                            <?php echo $this->getPriceHtml($_product, true) ?>
                                            <?php //echo Mage_Catalog_Block_Product::getPriceHtml($_product, true)  ?>
                                            <?php if ($_product->getTypeId() != 'grouped'): ?>
                                                <div class="price-per-attr">
                                                    <span><?php echo $this->__('Per') . " " . $_featuredHelper->getStockAndUnit($_product); ?></span>
                                                </div>
                                            <?php endif; ?>
                                        </div>
                                    </div>
                                    <div class="category-url">
                                        <?php
                                        $vwpr = '';
                                        if ($_product->getTypeId() == 'grouped' && $dispcount > 0) {
                                            $vwpr = $this->__('View Variants') . " " . "(" . $dispcount . ")";
                                        } else {
                                            $vwpr = $this->__('View Product');
                                        }
                                        ?>
                                        <a href="<?php echo $_product->getProductUrl(); ?>" title="<?php echo $vwpr; ?>"><?php echo $vwpr; ?></a>
                                    </div>
                                </div>
                                <div class="toshow bottom">
                                    <div class="hover_bottom">
                                        <?php if ($_product->getTypeId() != 'grouped'): ?>
                                            <div class="extra-stock">
                                                <div class="stock-limit">
                                                    <?php if ((int) Mage::getConfig()->getNode('default/combipac')->enable_stock && !$_product->isGrouped()) : ?>
                                                        <div class="checkstock list <?php echo $_product->getSku(); ?>" id="<?php echo $_product->getSku(); ?>">

                                                        </div>
                                                    <?php endif; ?>
                                                </div>
                                                <div class="action-container">
                                                    <div class="qty-wrapper">

                                                        <input type="text" name="qty" id="qty_<?php echo $_product->getSku(); ?>" min="1" maxlength="5" onkeypress="validateNumber(event)" value="1" title="<?php echo $this->__('Qty') ?>" class="input-text qty grid" />
                                                        <input type="hidden" class="hiddenstock"
                                                               id="stock_qty_<?php echo $_product->getSku(); ?>"
                                                               title="<?php echo $_product->getSku(); ?>"/>
                                                        <input type="hidden" class="hiddenstockstatus"
                                                               id="stock_qty_status_<?php echo $_product->getSku(); ?>"
                                                               value="<?php echo $_product->getArtikelstatus(); ?>"/>
                                                        <input type="hidden" class="hiddenindealpacking"
                                                               id="stock_qty_ideal_<?php echo $_product->getSku(); ?>"
                                                               value="<?php echo $_product->getIdealeverpakking(); ?>"/>
                                                        <input type="hidden" class="hiddenverkoopeenheid"
                                                               id="stock_qty_verkoopeenheid_<?php echo $_product->getSku(); ?>"
                                                               value="<?php echo $unit; ?>"/>
                                                        <input type="hidden" class="hiddenafwijkenidealeverpakking"
                                                               id="stock_qty_afwijkenidealeverpakking_<?php echo $_product->getSku(); ?>"
                                                               value="<?php echo $_product->getAfwijkenidealeverpakking(); ?>"/>
                                                        <input type="hidden" class="leverancier"
                                                               id="leverancier_<?php echo $_product->getSku(); ?>"
                                                               value="<?php echo $_product->getLeverancier(); ?>"/>
                                                    </div>
                                                    <div class="quantity-per-attr">
                                                        <span id="stock-label-<?php echo $_product->getSku(); ?>" class="stock-label-<?php echo $_product->getSku(); ?>">

                                                            <?php if (!(int) $_product->getData('afwijkenidealeverpakking')): ?>
                                                                <?php $stockInfo = $_product->getData('idealeverpakking'); ?>
                                                                <?php if ($stockInfo != '1'): ?>
                                                                    <?php echo '&nbsp;x&nbsp;' . $stockInfo; ?>
                                                                <?php endif; ?>
                                                                <?php
                                                            else :
                                                                $stockInfo = 1;
                                                                ?>
                                                            <?php endif; ?>


                                                            <?php echo Mage::helper('featured')->getStockUnit($stockInfo, $unit); //$_product->getData('verkoopeenheid');   ?>


                                                        </span></div>
                                                    <div class="button-container">
                                                        <button type="button"
                                                                    title="<?php echo $this->__('Add to Cart') ?>"
                                                                    class="button btn-cart ajax-cart"
                                                                    id="cart_button_<?php echo $_product->getSku(); ?>"
                                                                    data-url="<?php echo Mage::helper('checkout/cart')->getAddUrl($_product); ?>"
                                                                    data-id="<?php echo $_product->getId(); ?>">
                                                                <?php echo $this->__('Add to Cart') ?>
                                                            </button>
                                                    </div>
                                                </div>
                                            </div>
                                        <?php endif; ?>
                                        <span class="ajax_loading" id='ajax_loading<?php echo $_product->getId() ?>'><img
                                                src='<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>' alt="Loading.."/></span>
                                            <?php
                                            $viewVar = '';
                                            $viewVarClass = '';
                                            if ($_product->getTypeId() == 'grouped' && $dispcount > 0) {
                                                $viewVarClass = "view-variants";
                                                $viewVar = $this->__('View Variants') . " " . "(" . $dispcount . ")";
                                            } else {
                                                $viewVarClass = "view-product";
                                                $viewVar = $this->__('View Product');
                                            }
                                            ?>
                                        <div class="<?php echo $viewVarClass; ?>">
                                            <a href="<?php echo $_product->getProductUrl(); ?>"
                                               title="<?php echo $viewVar ?>"><?php echo $viewVar ?></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
        </div>
    </div>
    <script type="text/javascript">
        jQuery(document).ready(function ($) {

            /*var carouselID = '#special_carousel<?php echo $time; ?>';

            function mycarousel_initCallback(carousel) {
                $('#special_carousel_next<?php echo $time; ?>').bind('click', function () {
                    carousel.next();
                    return false;
                });
                $('#special_carousel_prev<?php echo $time; ?>').bind('click', function () {
                    carousel.prev();
                    return false;
                });

                if (typeof $('.product-slider-container').swipe !== 'undefined') {
                    $('.product-slider-container').swipe({
                        swipeLeft: function () {
                            carousel.next();
                        },
                        swipeRight: function () {
                            carousel.prev();
                        },
                        swipeMoving: function () {
                        }
                    });
                }
            };

            var mycarousel_reloadCallback = function (carousel) {
                if (!isResize('special_carousel_<?php echo $time; ?>'))
                    return;
                carousel.list = $(carouselID);
                var li = $(carouselID).children('li');
                carousel.list.css(carousel.lt, "0px");
                carousel.list.css(carousel.wh, $(li.get(0)).outerWidth(!0) * li.size() + 100);
                carousel.first = 1;
                carousel.last = $(carouselID).parent().width() / $(li.get(0)).outerWidth(!0);

            }
            if ($(window).width() >= 1224) {
                $('#special_carousel<?php echo $time; ?>').jcarousel({
                    scroll: 5,
                    initCallback: mycarousel_initCallback,
                    reloadCallback: mycarousel_reloadCallback,
                    buttonNextHTML: null,
                    buttonPrevHTML: null,
                    wrap: 'circular',
                    easing: 'linear'
                });
            }
            if ($(window).width() >= 768 && $(window).width() <= 1024) {
                $('#special_carousel<?php echo $time; ?>').jcarousel({
                    scroll: 3,
                    initCallback: mycarousel_initCallback,
                    reloadCallback: mycarousel_reloadCallback,
                    buttonNextHTML: null,
                    buttonPrevHTML: null,
                    wrap: 'circular',
                    easing: 'linear'
                });
            }
            if ($(window).width() <= 767) {
                $('#special_carousel<?php echo $time; ?>').jcarousel({
                    scroll: 1,
                    initCallback: mycarousel_initCallback,
                    reloadCallback: mycarousel_reloadCallback,
                    buttonNextHTML: null,
                    buttonPrevHTML: null,
                    wrap: 'circular',
                    easing: 'linear'
                });
                if ($(window).width() >= 600) {
                    $('#special_carousel<?php echo $time; ?>').jcarousel({
                        scroll: 2
                    });
                }
            }*/
        });
    </script>
<?php endif; ?>
