<?php
/**
 * ||GEISSWEB| EU VAT Enhanced
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the GEISSWEB End User License Agreement
 * that is available through the world-wide-web at this URL:
 * http://www.geissweb.de/eula/
 *
 * DISCLAIMER
 *
 * Do not edit this file if you wish to update the extension
 * to newer versions in the future. If you wish to customize the extension
 * for your needs please refer to our support for more information.
 *
 * @category    Mage
 * @package     Geissweb_Euvatgrouper
 * @copyright   Copyright (c) 2011 GEISS Weblösungen (http://www.geissweb.de)
 * @license     http://www.geissweb.de/eula/ GEISSWEB End User License Agreement
 */

class Geissweb_Euvatgrouper_Adminhtml_ReportController extends Mage_Adminhtml_Controller_Action
{

	public function indexAction()
	{
		$this->_title($this->__('Sales'))->_title($this->__('EU VAT Report'));
		$this->loadLayout();
		$this->_setActiveMenu('report/sales');
		//$this->_addContent($this->getLayout()->createBlock('euvatgrouper/adminhtml_report_moss_filter'));
		$this->_addContent($this->getLayout()->createBlock('euvatgrouper/adminhtml_report_moss'));
		$this->renderLayout();
	}

	public function gridAction()
	{
		$this->loadLayout();
		$this->getResponse()->setBody(
			$this->getLayout()->createBlock('euvatgrouper/adminhtml_report_moss')->toHtml()
		);
	}

	public function exportCsvAction()
	{
		$fileName = 'euvat_report.csv';
		$grid = $this->getLayout()->createBlock('euvatgrouper/adminhtml_report_moss');
		$this->_prepareDownloadResponse($fileName, $grid->getCsvFile());
	}

	public function exportXmlAction()
	{
		$fileName = 'euvat_report.xml';
		$grid = $this->getLayout()->createBlock('euvatgrouper/adminhtml_report_moss');
		$this->_prepareDownloadResponse($fileName, $grid->getXmlFile($fileName));
	}

}