<?php

/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/LICENSE-M1.txt
 *
 * @category   AW
 * @package    AW_Kbase
 * @copyright  Copyright (c) 2008-2010 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/LICENSE-M1.txt
 */

?>
<div class="kbase-block kbase-main-category">
    <h2 class="kbase-block-title"><?php printf(Mage::getStoreConfig('kbase/category/title')) ?></h2>

    <ul class="kbase-list level-0">
    <?php foreach($this->getCategories() as $category): ?>
        <li>
            <a href="<?php echo AW_Kbase_Helper_Url::getUrl(AW_Kbase_Helper_Url::URL_TYPE_CATEGORY, $category) ?>"><?php echo htmlspecialchars($category['category_name']) ?></a>
            <ul class="level-1">
            <?php foreach($category['articles'] as $article): ?>
                <li>
                    <a href="<?php echo AW_Kbase_Helper_Url::getUrl(AW_Kbase_Helper_Url::URL_TYPE_ARTICLE, $article, $category) ?>"><?php echo htmlspecialchars($article['article_title']) ?></a>
                </li>
            <?php endforeach ?>
            </ul>
        </li>
    <?php endforeach; ?>
    </ul>
</div>