<form id="storeitemform" method="post" action="">
	<div>
		<div class="your-order-list storeitem-green">
			<div class="heading">
					<h3>Op voorraadd</h3>
					<span>Velgende Werkdag af te halen</span>
			</div>
			<div class="list-items">
				<?php 
					$i=0;
					while($i <= 2):
				?>
				<div>
					<input type="hidden" value="481" name="storeitem">
					<div class="td-image">
						<a class="product-image" title="Kelfort Schroefnagel gedraaid  met platte  gladeeldraade kop  verzinkt 32x3 8mm" href="#">
							<img width="200" height="200" alt="Kelfort Schroefnagel gedraaid  met platte  gladeeldraade kop  verzinkt 32x3 8mm" data-srcx2="http://local.gyzs17.nl/media/catalog/product/cache/1/thumbnail/400x400/9df78eab33525d08d6e5fb8d27136e95/4/e/4e-23-f0-00-8a-51-be-67-5e-ee-0e-eb-22-d8-46-ec.jpg" src="http://local.gyzs17.nl/media/catalog/product/cache/1/thumbnail/200x200/9df78eab33525d08d6e5fb8d27136e95/4/e/4e-23-f0-00-8a-51-be-67-5e-ee-0e-eb-22-d8-46-ec.jpg">
						</a>
					</div>
					<div class="td-name">
						<div class="cart-sku">GY11515437</div>
						<h2 class="product-name">
							<a href="#">Kelfort Schroefnagel gedraaid  met platte  gladeeldraade kop  verzinkt 32x3 8mm</a>
						</h2>
					</div>				   
					<div class="a-center td-qty">
						<div class="stock-limit">
							<div id="1515437" class="checkstock-cart list">
								<div class="stock storeitem">
									<span class="green"></span>
									<span class="stock">2 stuks worden besteld </span>
									<span class="now-order">volgende werkdag af te halen</span>
								</div>
							</div>
						</div>						
						<input type="hidden" maxlength="12" class="input-text qty" title="Hoeveelheid" size="4" value="2" name="storeitem">
					</div>
				</div>
				<?php $i++; ?>
				<?php endwhile; ?>
			</div>
			<div class="collectionpoint">
				<div class="shipping-row">
					<h3><?php echo $this->__('Afhaalpunt')?></h3>
					<div class="collectionmethod-dropdown">
						<span class="current"><?php echo $this->__('Select an address') ?></span>
						<div class="collections-select-dropdown">
							<span></span>
							<ul>
								<li class="selected">guest user, sdfdgfg, rgegg,  123456, Nederland</li>
								<li>Lorem ipsum sit amit</li>
								<li>Lorem ipsum sit amit</li>
								<li>Lorem ipsum sit amit</li>
								<li>Lorem ipsum sit amit</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="your-order-list storeitem-orange">
			<div class="heading">
					<h3>Later af te halen</h3>
					<span>Verwacht vanaf 18 juni</span>
			</div>
			<div class="list-items">
				<?php 
					$i=0;
					while($i <= 2):
				?>
				<div>
					<input type="hidden" value="481" name="storeitem">
					<div class="td-image">
						<a class="product-image" title="Kelfort Schroefnagel gedraaid  met platte  gladeeldraade kop  verzinkt 32x3 8mm" href="#">
							<img width="200" height="200" alt="Kelfort Schroefnagel gedraaid  met platte  gladeeldraade kop  verzinkt 32x3 8mm" data-srcx2="http://local.gyzs17.nl/media/catalog/product/cache/1/thumbnail/400x400/9df78eab33525d08d6e5fb8d27136e95/4/e/4e-23-f0-00-8a-51-be-67-5e-ee-0e-eb-22-d8-46-ec.jpg" src="http://local.gyzs17.nl/media/catalog/product/cache/1/thumbnail/200x200/9df78eab33525d08d6e5fb8d27136e95/4/e/4e-23-f0-00-8a-51-be-67-5e-ee-0e-eb-22-d8-46-ec.jpg">
						</a>
					</div>
					<div class="td-name">
						<div class="cart-sku">GY11515437</div>
						<h2 class="product-name">
							<a href="#">Kelfort Schroefnagel gedraaid  met platte  gladeeldraade kop  verzinkt 32x3 8mm</a>
						</h2>
					</div>				   
					<div class="a-center td-qty">
						<div class="stock-limit">
							<div id="1515437" class="checkstock-cart list">
								<div class="stock storeitem">
									<span class="yellow"></span>
									<span class="stock">234 stuks worden besteld </span>
									<span class="now-order">levering 7 werkdagen</span>
								</div>
							</div>
						</div>						
						<input type="hidden" maxlength="12" class="input-text qty" title="Hoeveelheid" size="4" value="2" name="storeitem">
					</div>
				</div>
				<?php $i++; ?>
				<?php endwhile; ?>
			</div>
			<div class="collectionpoint">
				<div class="shipping-row">
					<h3><?php echo $this->__('Afhaalpunt')?></h3>
					<div class="collectionmethod-dropdown2">
						<span class="current"><?php echo $this->__('Select an address') ?></span>
						<div class="collections-select-dropdown2">
							<span></span>
							<ul>
								<li class="selected">guest user, sdfdgfg, rgegg,  123456, Nederland</li>
								<li>Lorem ipsum sit amit</li>
								<li>Lorem ipsum sit amit</li>
								<li>Lorem ipsum sit amit</li>
								<li>Lorem ipsum sit amit</li>
							</ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="delivery-bottom-controls">
				<div class="backlink">
			<a title="Terug" href="http://local.gyzs17.nl/multistepcheckout/index/login/"><?php echo $this->__('Back')?></a>
		</div>
            <button title="Ga verder" type="submit">
                <span><?php echo $this->__('Ga verder')?></span>
            </button>
	</div>
</form>
	<script type="text/javascript">
		jQuery(window).on('load', function(){
						jQuery('.collectionmethod-dropdown').click(function(){
				if(!jQuery(this).children('.collections-select-dropdown').is(':visible')){
					jQuery(this).children('.collections-select-dropdown').show();
				}
				else{
					jQuery(this).children('.collections-select-dropdown').hide();
				}
			});
			jQuery('.collections-select-dropdown ul li').click(function(){
				var currr = jQuery(this).html();
				var curid =	jQuery(this).attr('id');
				jQuery('.collectionmethod-dropdown .current').html(currr);
				/* jQuery('#outofstock-allshipping').val(curid);
				jQuery('#outofstock-allshipping option').removeAttr("selected");
				jQuery('#outofstock-allshipping option[value='+curid+']').attr("selected","selected"); */
				//jQuery(this).parents('.address-select-dropdown3').hide();
				jQuery('.collections-select-dropdown').slideUp();
				jQuery(this).addClass('selected');
				jQuery('.collections-select-dropdown ul li').not(jQuery(this)).removeClass('selected');
				console.log(currr);
			});
						jQuery('.collectionmethod-dropdown2').click(function(){
				if(!jQuery(this).children('.collections-select-dropdown2').is(':visible')){
					jQuery(this).children('.collections-select-dropdown2').show();
				}
				else{
					jQuery(this).children('.collections-select-dropdown2').hide();
				}
			});
			jQuery('.collections-select-dropdown2 ul li').click(function(){
				var currr = jQuery(this).html();
				var curid =	jQuery(this).attr('id');
				jQuery('.collectionmethod-dropdown2 .current').html(currr);
				/* jQuery('#outofstock-allshipping').val(curid);
				jQuery('#outofstock-allshipping option').removeAttr("selected");
				jQuery('#outofstock-allshipping option[value='+curid+']').attr("selected","selected"); */
				//jQuery(this).parents('.address-select-dropdown3').hide();
				jQuery('.collections-select-dropdown2').slideUp();
				jQuery(this).addClass('selected');
				jQuery('.collections-select-dropdown2 ul li').not(jQuery(this)).removeClass('selected');
				console.log(currr);
			});
		});
	 </script>