<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Brands
 */
?>
<?php
    $iconWidth = max(0, intval($this->getIconWidth()));
    $iconHeight = max(0, intval($this->getIconHeight()));
    $iconClass = str_replace(' ', '.',$this->getIconClass());
?>
<style>
    .ambrands_leftmenu img<?php echo $iconClass?> {
        <?php if ($iconWidth): ?>
        max-width: <?php echo $iconWidth;?>px;
        <?php endif;?>
        <?php if ($iconHeight): ?>
        max-height: <?php echo $iconHeight;?>px;
        <?php endif;?>
</style>

<div class="amasty-sidebar-filter-wrap block block-layered-nav block-layered-nav--no-filters">
    <div class="block-content toggle-content">
        <div class="filter-item-wrap">
            <div class="filter-item-title">
                <?php echo $this->__('Brands') ?>
                <span class="arrow-toggle">
                    <i class="fa fa-angle-up" aria-hidden="true"></i>
                </span>
            </div>
            
            <div class="filter-items">
                <ol class="m-filter-item-list">
                    <?php foreach ($this->getItems() as $item) :?>
                        <li class="ambrands_leftmenu"><?php echo $this->getBrandLabelUrl($item);?></li>
                    <?php endforeach;?>
                </ol>
            </div>
            <div class="ambrands_button">
                <button class="button all-brand-btn" type="button" onclick="setLocation('<?php echo Mage::helper('ambrands')->getBrandsPageUrl(); ?>')">
                    <span><span>
                <?php echo $this->__('View All') ?></span></span></button>
            </div>
        </div>
    </div>
</div>
