<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2017 Amasty (https://www.amasty.com)
 * @package Amasty_Brands
 */
?>
<?php
/**
 * @var Amasty_Brands_Block_Slider $this
 */
?>
<?php
$items          = $this->getItems();
$sliderOptions  = $this->getSliderOptions();
$hlp            = Mage::helper('ambrands');
$showLabel      = $this->getShowLabel();
$iconUrl        = $hlp->getImageUrl('slider');
$showPagination = $this->getShowPagination();
$showButtons    = $this->getShowButtons();
$imgWidth       = $this->getImageWidth() ? $this->getImageWidth() : Amasty_Brands_Block_Slider::DEFAULT_IMG_WIDTH;
$imgHeight      = $this->getImageHeight();
$headerColor      = '#' . Mage::getStoreConfig('ambrands/styles/slider_color');
$headerBackground = '#' . Mage::getStoreConfig('ambrands/styles/slider_background');
$buttonWidth    = 40;
$itemsPerView   = $this->getItemsNumber();
$sliderWidth    = $this->getSliderWidth() ? $this->getSliderWidth() : ($imgWidth + 10) * $itemsPerView;
$widthPerSlide  = $sliderWidth / $itemsPerView;
?>
<style>
    .amslider {
        max-width: <?php echo $buttonWidth * 2 + $sliderWidth; ?>px;
        padding: 0 <?php echo $buttonWidth?>px;
    }
    .amslider .swiper-slide .swiper-brand img {
        <?php if ($imgWidth): ?>
            max-width: <?php echo $imgWidth;?>px;
        <?php endif;?>
        <?php if ($imgHeight): ?>
            max-height: <?php echo $imgHeight;?>px;
        <?php endif;?>
    }
    .amslider-container .ambrands-header-container{
        background: <?php echo $headerBackground?>;
    }
    .amslider-container .ambrands-header-container span {
        color: <?php echo $headerColor?>;
    }
</style>
<div class="product-title-name">
  <h1 class="h1"><?php echo Mage::getStoreConfig('ambrands/brands_landing/title'); ?></h1>
</div>
<?php //echo $this->getLayout()->getBlock('breadcrumbs')->toHtml(); ?>
<div class="amslider-container">
    <!-- <div class="ambrands-header-container">
        <div class="ambrands-header">
            <span><?php //echo Mage::getStoreConfig('ambrands/slider/title'); ?></span>
        </div>
    </div> -->
    
<div class="amslider <?php if($showLabel) echo ' show-label'?>">
  <?php if ($showPagination): ?><div class="swiper-pagination"></div><?php endif;?>
  <div class="swiper-container">
    <div class="swiper-wrapper">
      <?php foreach ($items as $brand): ?>
        <a href="<?php echo $brand->getUrl()?>"class="swiper-slide">
            <div class="swiper-brand <?php if ($showLabel) echo ' brand-label' ?>">
              <img src="<?php echo $this->getImgPath($brand); ?>" alt="<?php echo $brand->getName()?>" />
                <?php if ($showLabel): ?>
                  <div class="brand-title"><?php echo $brand->getName()?></div>
                <?php endif; ?>
            </div>
        </a>
      <?php endforeach;?>
    </div>
  </div>
    <?php if ($showButtons): ?>
    <div class="swiper-button-prev swiper-button"><i class="fa fa-angle-left" aria-hidden="true"></i></div>
    <div  class="swiper-button-next swiper-button"><i class="fa fa-angle-right" aria-hidden="true"></i></div>
    <?php endif; ?>
</div>
</div>
<script type="text/javascript">
  document.observe("dom:loaded", function () {
    var swiper = new Swiper('.swiper-container', {
      <?php foreach ($sliderOptions as $option => $value) {
        echo $option . ':' . $value . ",";
      }?>
      breakpoints: {
      <?php for($i = 1; $i < $itemsPerView; $i++) :?>
        <?php echo ($i + 1) * ($imgWidth + 20 + 10) + $buttonWidth * 2; ?> : {
          slidesPerView: <?php echo $i ?>
          },
        <?php endfor; ?>
      },
      nextButton: '.swiper-button-next',
      prevButton: '.swiper-button-prev',
      spaceBetween: 10
    });
  });


// jQuery(document).ready(function(){

//   setTimeout (function (){
//       jQuery('.swiper-button-next.swiper-button').trigger('click');
//   },500)

  

//   var $grid = jQuery('.brands-filter-wrap').isotope({
//     itemSelector: '.brands-filter-letter-outer',
    
//   });

//   // filter items on button click
//   jQuery('.letters-box').on( 'click', 'a', function() {
//     var filterValue = jQuery(this).attr('data-filter');
//     $grid.isotope({ filter: filterValue });
//   });

//   jQuery(window).trigger('resize');
  

//   });


jQuery(window).on('resize',function() {

    var win = jQuery(this);

      
     if(win.width() >= 760 && win.width() < 992) {
          paginationslider(15);
      } else if (win.width() <= 759 && win.width() > 480) {
          paginationslider(11);
      } else if (win.width() < 479) {
        paginationslider(5);
      } else {
        paginationslider(100);
      }
      
});


function paginationslider(items) {
    var start = 0;
    var end = items;
    var len = $j('.letters-box a').length;

    $j('.letters-box a').hide().slice(start, end).show();

    $j('.letter-button-next').on('click', function () {
        if (end < len) {
            start++;
            end++;
            $j('.letters-box a').hide().slice(start, end).show();
        }
    });

    $j('.letter-button-prev').on('click', function () {
        if (start > 0) {
            start--;
            end--;
            $j('.letters-box a').hide().slice(start, end).show();
        }
    });
}



</script>