<table cellspacing="0" cellpadding="8" width="100%">
    <tbody>
        <?php echo $this->renderTotals(); ?>
        <?php echo $this->renderTotals('footer'); ?>
    </tbody>
</table>
<div class="divider"></div>
<div class="order-totals-bottom">
	<p>
        <label for="notify_customer" class="normal"><?php echo Mage::helper('sales')->__('Append Comments') ?></label>
        <input type="checkbox" id="notify_customer" name="order[comment][customer_note_notify]" value="1" <?php if($this->getNoteNotify()): ?>checked="true"<?php endif; ?>/>
    </p>
    <?php if ($this->canSendNewOrderConfirmationEmail()): ?>
    <p>
        <label for="send_confirmation" class="normal"><?php echo Mage::helper('techtwo_salesquotes')->__('Email Confirmation') ?></label>
        <input type="checkbox" id="send_confirmation" name="order[send_confirmation]" value="1" checked="checked"/>
    </p>    
    <?php endif; ?>

    <?php $checked = ((Mage::getSingleton('adminhtml/session_quote')->getConvertOrderQuote() != 0) || (true &&  $this->getQuote()->getIsCartAuto()!=1)); ?>
    <p>
        <label for="edit_send_quote" class="normal" title="<?php echo Mage::helper('techtwo_salesquotes')->__('Check to save as quote, uncheck to save as order') ?>"><?php echo Mage::helper('techtwo_salesquotes')->__('Edit and Send Quote') ?></label>
        <input type="checkbox" id="edit_send_quote" name="edit_send_quote" value="1"<?php if ($checked): ?>checked="checked"<?php endif ?> />
    </p>

    <p><?php echo $this->getButtonHtml(Mage::helper('techtwo_salesquotes')->__('Save quote/order'),'order.submit()','save'); ?></p>
</div>

<script type="text/javascript">
//<![CDATA[
var sendEmailCheckbox = $('send_confirmation');
if (sendEmailCheckbox) {
    Event.observe(sendEmailCheckbox, 'change', notifyCustomerUpdate);
    notifyCustomerUpdate();
}

function notifyCustomerUpdate() {
    var sendEmailCheckbox = $('send_confirmation');
    var notifyCustomerCheckbox = $('notify_customer');
    if (!sendEmailCheckbox || !notifyCustomerCheckbox)
        return;
    notifyCustomerCheckbox.disabled = !sendEmailCheckbox.checked;
}
//]]>
</script>
