<?php
/**
 * @category    design
 * @package     base_default
 * @copyright   Copyright (c) 2012 Magento Inc. (http://www.magentocommerce.com)
 * @license     http://opensource.org/licenses/afl-3.0.php  Academic Free License (AFL 3.0)
 */
/**
 * Grouped product data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 * @see Mage_Catalog_Block_Product_View_Type_Grouped
 */
?>
<?php $_helper = $this->helper('catalog/output');
$this->setPreconfiguredValue();
$_product = $this->getProduct();
$_featuredHelper = Mage::helper('featured');
$_associatedProducts = $this->getAssociatedProducts();
$_hasAssociatedProducts = count($_associatedProducts) > 0;

$category = Mage::registry('current_category');

if (!$category) {
	$categories = $_product->getCategoryIds();
	$category = Mage::getModel('catalog/category')->load(end($categories));
}

/* Returns comma separated ids */
$subcats = $category->getChildren();

$CatCustomFilter = array();
if ($subcats) {
	foreach (explode(',', $subcats) as $subCatid) {
		$_category = Mage::getModel('catalog/category')->load($subCatid);
		$CatCustomFilter[$subCatid] = $_category->getCustomFilters();
	}
}

if (count($CatCustomFilter) == 0) {
	$CatCustomFilter[$category->getId()] = $category->getCustomFilters();
}

$custom_filters = array();
$ProductCat = $_product->getCategoryIds();
foreach ($ProductCat as $_cat) {
	if (array_key_exists($_cat, $CatCustomFilter)) {
		$custom_filters = explode(",", $CatCustomFilter[$_cat]);
	}
}

$dispcount = count($_associatedProducts);
?>
<?php if(Mage::helper('common')->isMobile()){ ?>
    <!-- <div class="grouped-products-filters clearfix">
        <a href="#" class="filter-link"><i class="fa fa-chevron-down"></i> <?php //echo $this->__('Filter') ?></a>
        <a href="#" class="filter-link"><i class="fa fa-chevron-down"></i> <?php //echo $this->__('Filter') ?></a>
    </div>
    <div class="res-fltr grouped-fltr">
        <a href="#" class="filterclose fa fa-close"></a>
        <div class="block-content layernav">
            <dl id="narrow-by-list">
                <dt class="noncategorydt custom">
                    <span class="fltrs noncategory"><span> Breedte (mm)</span></span>
                    <span class="fltrarw noncategory"></span>
                </dt>
                <dd class="noncategory custom">
                    <ol class="m-filter-item-list ">
                        <li>
                            <input id="" type="checkbox" class="layered-checkbox" name="" onclick="" style="position:relative; opacity:1;">
                            <label for=""><span class="mfilter">46</span></label>
                            <span class="lay-count">6</span>
                        </li>
                    </ol>
                    <a href="#" class="shopby_more" style="display: block;">Toon meer</a>
                </dd>
            </dl>
        </div>
    </div> -->
<?php } ?>
    <div class="mini-products-list-grouped" id="block-related">
    	<div class="grouped-detail-container clearfix">
    		<div class="grouped-detail-image">
    			<?php
    				/**
    				 * for Display photo of the group product if it is not available.
    				*/
    				$imageSrc="";
    				$image=$_product->getData('small_image');
    				if(isset($image) && $image!="no_selection"){
    					$imageSrc=$this->helper('catalog/image')->init($_product, 'small_image')->resize(138);
    				} else {
    					if ($_product->isGrouped()){
    						foreach($_associatedProducts as $prod){
    							$prod = $prod->load($prod->getId());
    							$image = $prod->getData('small_image');
    							if(isset($image) && $image!="no_selection"){
    								$imageSrc=$this->helper('catalog/image')->init($prod, 'small_image')->resize(138);
    								break;
    							}
    						}
    						if($imageSrc==""){
    							$imageSrc=$this->helper('catalog/image')->init($_product, 'small_image')->resize(138);
    						}
    					} else {
    						$imageSrc=$this->helper('catalog/image')->init($_product, 'small_image')->resize(138);
    					}
    				}
    			?>
    			<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image">
    				<img itemprop="image" src="<?php echo $imageSrc; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
    			</a>
    		</div>
    		<div class="grouped-detail-info">
    			<h3><?php
    				if ($dispcount > 0) {
    					echo $this->__('Product with') . " " . $dispcount . " " . $this->__('variants');
    				} else {
    					echo $this->__('Grouped Product');
    				}
    				?></h3>
    			<div class="group-readmore">
    				<div class="groupmore" itemprop="description" id="grpproddesc"><?php echo html_entity_decode(htmlentities($_product->getDescription(), ENT_QUOTES, 'UTF-8')); ?></div>
    			</div>
    		</div>
    		<div class="grouped-detail-price">
    			<div class="stuckinfo">
    				<?php echo $this->__('per') . " " . Mage::helper('featured')->getFirstAssociativeItem($_product,'list') . " vanaf"; ?>
    			</div>
    			<?php $_item = Mage::helper('featured')->getFirstAssociativeItemPrice($_product); ?>
    			<?php if(!empty($_item)) : ?>
    				<?php if ($this->getCanShowProductPrice($_item)): ?>
    					<?php echo $this->getPriceHtml($_item, true) ?>
    					<?php echo $this->getTierPriceHtml($_item) ?>
    				<?php endif; ?>
    				<div class="no-display" itemprop="offers" itemscope="" itemtype="http://schema.org/Offer">
    					<span itemprop="price"><?php echo Mage::helper('common')->getProductInclPrice($_item); ?></span>
    					<span itemprop="priceCurrency"><?php echo Mage::app()->getStore()->getCurrentCurrencyCode(); ?></span>
    					<link itemprop="availability" href="http://schema.org/InStock">
    				</div>
    			<?php endif; ?>
    		</div>
    		<div class="grouped-assoproducts">
    			<?php $dispcount = count($_associatedProducts); ?>
    			<?php echo $dispcount; ?>
    		</div>
    	</div>
    	<div class="mobile-grouped-detail-container clearfix">
    		<div class="grouped-detail-info">
    			<h3>
    				<?php
    				if ($dispcount > 0) {
    					echo $this->__('Product with') . " " . $dispcount . " " . $this->__('variants');
    				} else {
    					echo $this->__('Grouped Product');
    				}
    				?>
    			</h3>
    			<div class="group-readmore">
    				<div class="groupmore" id="grpproddescmobile"><?php echo html_entity_decode(htmlentities($_product->getDescription(), ENT_QUOTES, 'UTF-8')); ?></div>
    			</div>
    		</div>
    		<div class="mobilegrp-top">
    			<div class="grouped-detail-image">
    				<a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>" class="product-image"><img src="<?php echo $imageSrc; ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></a>
    			</div>
    			<div class="grouped-detail-price">
    			   <div class="stuckinfo">
    				<?php echo $this->__('per') . " " . Mage::helper('featured')->getFirstAssociativeItem($_product,'list') . " vanaf"; ?>
    				</div>
    				<?php $_item = Mage::helper('featured')->getFirstAssociativeItemPrice($_product); ?>
    				<?php if(!empty($_item)) : ?>
    					<?php if ($this->getCanShowProductPrice($_item)): ?>
    						<?php echo $this->getPriceHtml($_item, true) ?>
    						<?php echo $this->getTierPriceHtml($_item) ?>
    					<?php endif; ?>
    				<?php endif; ?>
    			</div>
    			<div class="grouped-assoproducts">
    				<?php $dispcount = count($_associatedProducts); ?>
    				<?php echo $dispcount; ?>
    			</div>
    		</div>
    	</div>
        <ul class="mb-grouped-products-list clearfix">
            <?php if ($_hasAssociatedProducts): ?>
                <?php foreach ($_associatedProducts as $_item): ?>
                    <?php $_item = $_item->load($_item->getId()); ?>
                    <li class="item-inner clearfix">
                        <div class="clearfix">
                        <div class="device-left-col">
                            <div class="group-product-img clearfix">
                            <div class="oproduct-image">
                                <a href="<?php echo Mage::getBaseUrl() . $_item->getUrlPath(); ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(80) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                            </div>
                            <div class="group-product-title-sku">
                                <div class="clearfix">
                                    <div class="group-product-label"><?php echo $this->__('Sku') ?> :</div>
                                    <div class="group-product-val">
                                         <a class="text-underline product-sku" href="<?php echo Mage::getBaseUrl() . $_item->getUrlPath(); ?>">
                                            <span><?php echo Mage::helper('common')->getGYZSSku($_item['sku']); ?></span>
                                         </a>
                                    </div>
                                </div>
                                <div class="clearfix">
                                   <div class="group-product-label"><?php echo $this->__('Product Name') ?> :</div>
                                   <div class="group-product-val">
                                        <a href="<?php echo Mage::getBaseUrl() . $_item->getUrlPath(); ?>" class="product-name pname" title="<?php echo $this->htmlEscape($_item->getName()) ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                                   </div>
                                </div> 
                            </div>
                        </div>
                        <?php $filtercols=0; if (isset($custom_filters) && strlen($custom_filters[0]) > 0) : ?>
                            <div class="group-filter-data">
                                    <?php foreach ($custom_filters as $f) : 
                                        $attText = '';
                                        $attVal = '-';

                                        $objAttributeVal = $_item->getResource()->getAttribute($f);
                                        if(!empty($objAttributeVal)) {
                                            $attText = $objAttributeVal->getFrontendLabel($f);
                                            $attVal = $_item->getAttributeText($f);
                                        }
                                        if(empty($attVal) || $f == 'verpakkingseanhoeveelheid_'){
                                            continue;
                                        }
                                        
                                    ?>  
                                    <div class="clearfix">
                                        <div class="group-product-label"><?php echo ucfirst(strtolower($attText)); ?></div>
                                        <div class="group-product-val"> : <?php echo $attVal; ?></div>
                                    </div>
                                <?php endforeach; ?>
                            </div>
                        <?php endif; ?>
                        </div>
                        <div class="device-right-col">
                            <div class="mb-group-product-stock">
                            <div class="clearfix mb-5">
                                <div class="group-product-label"><?php echo $this->__('Stock') ?> :</div>
                                <div class="group-product-val">
                                    <?php $unit = Mage::helper('featured')->getProductUnit($_item->getData('verkoopeenheid')); ?>
                                        <?php if ((int) Mage::getConfig()->getNode('default/combipac')->enable_stock) : ?>
                                                <div class="extra-stock">
                                                        <span class="checkstock grouped hover_<?php echo $_item->getSku(); ?> list" id="<?php echo $_item->getSku(); ?>"></span>
                                                </div>
                                        <?php endif; ?>
                                </div>
                            </div>
                            <div class="clearfix">
                                <div class="group-product-label"><?php echo $this->__('Price') ?> :</div>
                                <div class="group-product-val">
                                    <?php echo $this->getPriceHtml($_item, true) ?>
                                </div>
                            </div>
                        </div>
                        <div class="mb-group-product-price clearfix">
                            <div class="product-qty-icons clearfix"><button type="button" class="fa fa-plus qtyincr"></button> <button type="button" class="fa fa-minus qtyincr"></button></div>
                            <div class="add-to-cart">
                                <div class="qty-container clearfix">
                                    <?php $unit = Mage::helper('featured')->getProductUnit($_item->getData('verkoopeenheid')); ?>
                                    <!-- <label for="qty"><?php //echo $this->__('Qty') ?>:</label> -->
                                    <input type="hidden" name="qty" id="qty_<?php echo $_item->getSku(); ?>" maxlength="5" onkeypress="validateNumber(event)" value="<?php echo max($this->getProductDefaultQty() * 1, 1) ?>" title="<?php echo $this->__('Qty') ?>" class="input-text qty grid" />
                                    <input type="hidden" class="hiddenstock"
                                               id="stock_qty_<?php echo $_item->getSku(); ?>"
                                               title="<?php echo $_item->getSku(); ?>"/>
                                    <input type="hidden" class="hiddenstockstatus"
                                               id="stock_qty_status_<?php echo $_item->getSku(); ?>"
                                               value="<?php echo $_item->getArtikelstatus(); ?>"/>
                                    <input type="hidden" class="hiddenindealpacking"
                                               id="stock_qty_ideal_<?php echo $_item->getSku(); ?>"
                                               value="<?php echo $_item->getIdealeverpakking(); ?>"/>
                                    <input type="hidden" class="hiddenverkoopeenheid"
                                               id="stock_qty_verkoopeenheid_<?php echo $_item->getSku(); ?>"
                                               value="<?php echo $unit; ?>"/>
                                    <input type="hidden" class="hiddenafwijkenidealeverpakking"
                                               id="stock_qty_afwijkenidealeverpakking_<?php echo $_item->getSku(); ?>"
                                               value="<?php echo $_item->getAfwijkenidealeverpakking(); ?>"/>
                                    <input type="hidden" class="leverancier"
                                               id="leverancier_<?php echo $_item->getSku(); ?>"
                                               value="<?php echo $_item->getLeverancier(); ?>"/>
                                </div>

                                <button type="button" title="<?php echo $this->__('Buy Now') ?>" id="cart_button_<?php echo $_item->getSku(); ?>" class="button btn-cart ajax-cart" data-url="<?php echo $this->getAddToCartUrl($_item); ?>" data-id="<?php echo $_item->getId(); ?>"><i class="fa fa-shopping-cart"></i> <?php echo $this->__('Buy') ?> <strong>1 <?php $stockInfo=1; if (!(int) $_item->getData('afwijkenidealeverpakking')): ?><?php $stockInfo = $_item->getData('idealeverpakking'); if ($stockInfo != '1'): ?> <?php echo '&nbsp;x&nbsp;' . $stockInfo; ?><?php endif; endif; ?> <?php echo Mage::helper('featured')->getStockUnit($stockInfo, $unit); ?> </strong></button>
                            </div>
                        </div> 
                        </div>
                        </div>
                    </li>
                <?php endforeach; ?>
            <?php endif; ?>
        </ul>
        <script type="text/javascript">
            jQuery(document).on('click', '.qtyincr', function() {
                var qtyInput = jQuery(this).parent().next().find('.qty');
                var buttonText = jQuery(this).parent().next().find('.ajax-cart strong');
                var verkoopeenheid = jQuery(this).parent().next().find('.hiddenverkoopeenheid').val().toLowerCase();
                var afwijkenidealeverpakking = jQuery(this).parent().next().find('.hiddenafwijkenidealeverpakking').val();
                var idealeverpakking = jQuery(this).parent().next().find('.hiddenindealpacking').val();
                var stockLabel = verkoopeenheid.split("|");
                var qty = qtyInput.val();
                if(isNaN(qty) || qty ==''){
                    qty = 0;
                }
                if(jQuery(this).hasClass('fa-plus')){
                    qty = parseFloat(qty) + 1;
                } else {
                    qty = parseFloat(qty) - 1;
                    if(qty==0) {
                        qty = 1;
                    }
                }
                qtyInput.val(qty);
                if(qty == 1){
                    verkoopeenheid = stockLabel[0];
                } else {
                    verkoopeenheid = stockLabel[1];
                }
                if(afwijkenidealeverpakking == 0){
                    verkoopeenheid = '&nbsp;x&nbsp;' + idealeverpakking + ' ';
                    if(idealeverpakking == 1){
                        verkoopeenheid += stockLabel[0];
                    } else {
                        verkoopeenheid += stockLabel[1];
                    }
                }

                jQuery(qtyInput).trigger('keyup');
                buttonText.html(qty + ' ' + verkoopeenheid);
            });

            jQuery(".group-filter-data").each(function(){
              var totContent = jQuery(this).find('.clearfix').size();
              if (totContent == 0) {
                jQuery(this).hide();
              }
            })
            
            jQuery(document).on('click', '.mb-grouped-products-list .add-to-cart button', function() {
                jQuery(".header-top.fixed-head").removeClass("header-up").addClass("header-down");
            });
        </script>

    	<div class="groupproductlinks">
    		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('grouplinks')->toHtml(); ?>
    	</div>
    </div>

    <script type="text/javascript">
    	jQuery(window).on("load", function () {
    		//Read more using readmore.js
    		jQuery('.groupmore').readmore({
    			speed: 1500,
    			collapsedHeight: 130,
    			moreLink: "<a href='#' class='morelink3'><?php echo $this->__("Read group more") ?></a>",
    			lessLink: "<a href='#' class='morelink3'><?php echo $this->__("Read group less") ?></a>",
    			afterToggle: function (trigger, element, expanded)
    			{
    				var ht = jQuery('header.fixed').height() + 150;
    				if (!expanded) { // The "Close" link was clicked
    					jQuery('html, body').animate({scrollTop: jQuery('.groupmore').offset().top - ht}, 100);
    					jQuery('.morelink3').removeClass('opened');
    				} else {
    					jQuery('.morelink3').addClass('opened');
    				}
    			}
    		});
    		var scrollFlag = 0;
    	});

    </script>
<?php

// Helios_Gtm module enable and setting enable for gtm than only script execute
if(Mage::helper('gtm')->getEnabled()){
	$customerEmail =  Mage::helper('featured')->getCustomerEmail();
?>
	<script type="text/javascript">
		//<![CDATA[
		jQuery(window).on("load", function(){
			var counter = 0;
			var productData = [];
			jQuery( ".pname" ).each(function() {
				var product = {};
				product.id = jQuery( this ).parent().parent().prev().find('span').text();
                if(product.id != ''){
				    productData.push(product);
				    counter++;
                }
			});
			dataLayer.push({                      
				'event': 'crto_listingpage',
				crto: {            	
					'email': '<?php echo $customerEmail ?>',
					'products': productData
				}
			});
		});
		//]]>
	</script>
<?php } ?>