<?php 

/*
* Change by Parth
* No need of $customerAddressId / $customerAddress variable or object as
* we can get address all data with $this
*/

$customer = Mage::getSingleton('customer/session')->getCustomer();
$_countries = Mage::helper('common')->getCountries();
$defaultCountry = ($this->getAddress()->getCountry())?$this->getAddress()->getCountry():Mage::helper('core')->getDefaultCountry();
// $customerAddressId = $customer->getDefaultBilling();
// $customerAddress = Mage::getModel('customer/address')->load($customerAddressId);

// $customerData = Mage::getModel('customer/customer')->load($customer->getId());//echo "<pre>"; print_r($this->getAddress()->getData()) ;
//echo "<pre>"; print_r($this->getAddress()->getData()); exit;
?>
<fieldset class="group-select fieldset" id="co-billing-form">
    <?php if (!Mage::getSingleton('customer/session')->isLoggedIn()): ?>
        <p class="login-link">
            <a id="login-link" href="<?php echo $this->getUrl('salesquotes/quote/loginCustomer'); ?>"><?php echo $this->__('Already registered? You can login here.'); ?></a>
        </p>
    <?php endif; ?>

    <div id="billing-address-form">
        <input type="hidden" name="billing[address_id]" value="<?php echo $this->getAddress()->getId() ?>" id="billing:address_id" />
        <ul class="form-list">
            <li class="fields">
                <div class="field">
                    <label for="billing:country_id" class="required"><?php echo $this->__('Country') ?></label>
                    <?php if (count($_countries) > 0): ?>
                        <select name="country_id" id="country" class="accnt-country-select">
                            <option value="">-- Please Select --</option>
                            <?php foreach ($_countries as $_country): ?>
                                <option value="<?php echo $_country['value'] ?>" <?php  if ($_country['value'] == $defaultCountry):?> selected="selected" <?php endif;?>>
                                    <?php echo $_country['label'] ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    <?php endif; ?>
                </div>
            </li>
            <li>
                <div class="field">
                    <label for="billing:company_type" class="required"><?php echo $this->__('Order Type') ?></label>
                    <div class="input-box radio-selection company-type">
                        <input type="radio" name="billing[company_type]" id="billing:company_type_personal" value="personal"  onclick="displayField(this.value);"<?php if ($this->getAddress()->getCompanyType() == 'personal'): ?>checked="checked" <?php else: ?> checked="checked"<?php endif; ?> />
                        <label for="billing:company_type_personal"><?php echo $this->__('Personal'); ?></label>
                        <input type="radio" name="billing[company_type]" id="billing:company_type_business" value="business" onclick="displayField(this.value);" <?php if ($this->getAddress()->getCompanyType() == 'business'): ?>checked="checked"<?php endif; ?>  />
                        <label for="billing:company_type_business"><?php echo $this->__('Business'); ?></label>

                    </div>
                </div>
                    </li>
                    <li class="fields" id="business-company"  style="display:none;">
                        <div class="field">
                            <label for="billing:company"><?php echo $this->__('Company name') ?></label>
                            <div class="input-box">
                                <input type="text" id="billing:company" name="billing[company]" value="<?php echo $this->escapeHtml($this->getAddress()->getCompany()) ?>" title="<?php echo $this->__('Company') ?>" class="input-text singles company <?php echo $this->helper('customer/address')->getAttributeValidationClass('company') ?>" placeholder="<?php echo $this->__('Company name') ?>" onfocus="this.placeholder = '';" onblur="this.placeholder = '<?php echo $this->__('Company name') ?>';" />
                            </div>
                        </div>
                    </li>
                    <?php if ($this->helper('customer/address')->isVatAttributeVisible()) : ?>
                        <li class="fields" id="business-vat" style="display:none;">
                            <label for="billing:vat_id"><?php echo $this->__('VAT Number') ?></label>
                            <div class="input-box">
                                <input type="text" id="billing:vat_id" name="billing[vat_id]" value="<?php echo $this->escapeHtml($this->getAddress()->getVatId()) ?>" title="<?php echo $this->__('VAT Number') ?>" class="input-text vtnumber <?php echo $this->helper('customer/address')->getAttributeValidationClass('vat_id') ?>" placeholder="<?php echo $this->__('VAT Number') ?>" onfocus="this.placeholder = '';" onblur="this.placeholder = '<?php echo $this->__('VAT Number') ?>';"  />
                            </div>
                        </li>
                    <?php endif; ?>
                    <li class="fields" id="business-ref" style="display:none;">
                        <label for="billing:referentie"><?php echo $this->__('Reference') ?></label>
                        <div class="input-box">
                            <input type="text" id="billing:referentie" name="billing[referentie]" value="<?php echo $this->escapeHtml($this->getAddress()->getReferentie()) ?>" title="<?php echo $this->__('Referentie Number') ?>" class="input-text referencenumber " placeholder="<?php echo $this->__('Reference') ?>" onfocus="this.placeholder = '';" onblur="this.placeholder = '<?php echo $this->__('Reference') ?>';"  />
                        </div>
                    </li>
            <li class="fields"><?php echo $this->getLayout()->createBlock('customer/widget_name')->setTemplate('salesquotes/quote/quote/widget/name.phtml')->setObject($this->getAddress())->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml() ?></li>
            <li class="fields">
                <div class="field other-input input-postcode">
                    <label for="billing:postcode" class="required"><?php echo $this->__('Zip/Postal Code') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Zip/Postal Code') ?>" name="billing[postcode]" id="billing:postcode" value="<?php echo $this->htmlEscape($this->getAddress()->getPostcode())   ?>" class="input-text validate-zip-international required-entry" />
                    </div>
                </div>
                        <div class="field other-housenumber input-postcode">
                            <label for="billing:housenumber" class="required"><?php echo $this->__('Housenumber') ?></label>
                            <div class="input-box codepost">
                                <input type="text" title="<?php echo $this->__('Housenumber') ?>" name="billing[housenumber]" id="billing:housenumber" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" class="input-text singles postcode validate-zip-international " placeholder="<?php echo $this->__('12') ?>" onfocus="this.placeholder = '';" onblur="this.placeholder = '<?php echo $this->__('12') ?>';"  />
                            </div>
                        </div>
            </li>    
            <li class="fields">
                <div class="field">
                    <label for="billing:street1"><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][]" id="billing:street1" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(1)) ?>" class="required-entry input-text" placeholder="<?php echo $this->__('Street Address') ?>" onfocus="this.placeholder = '';
                               " onblur="this.placeholder = '<?php echo $this->__('Street Address') ?>';
                               " />
                    </div>
                </div>
                <div class="field" style="display:none;">
                    <label for="billing:street2"><?php echo $this->__('Street Address') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('Street Address') ?>" name="billing[street][1]" id="billing:street2" value="<?php echo $this->htmlEscape($this->getAddress()->getStreet(2)) ?>" class="required-entry input-text" placeholder="<?php echo $this->__('Street Address') ?>" onfocus="this.placeholder = '';
                               " onblur="this.placeholder = '<?php echo $this->__('Street Address') ?>';
                               " />
                    </div>
                </div>
            </li>


            <li class="fields">
                <div class="field">
                    <label for="billing:city" class="required"><?php echo $this->__('City') ?></label>
                    <div class="input-box">
                        <input type="text" title="<?php echo $this->__('City') ?>" name="billing[city]" value="<?php echo $this->htmlEscape($this->getAddress()->getCity()) ?>" class="input-text required-entry" id="billing:city" placeholder="<?php echo $this->__('City') ?>" onfocus="this.placeholder = '';
                               " onblur="this.placeholder = '<?php echo $this->__('City') ?>';
                               " />
                    </div>
                </div>
            </li>
             <li class="fields">
                <?php //if (!$this->isCustomerLoggedIn()): ?>
                    <div class="field">
                        <label for="billing:email" class="required"><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="billing[email]" id="billing:email" value="<?php echo $this->htmlEscape($customer->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" placeholder="<?php echo $this->__('Email Address') ?>" onfocus="this.placeholder = '';" onblur="this.placeholder = '<?php echo $this->__('Email Address') ?>';"  />
                        </div>
                    </div>
                <?php // endif ?>
            </li>  
            <li class="fields">

                <div class="field telephonefield">
                    <label for="billing:telephone"><?php echo $this->__('Telephone') ?></label>
                    <div class="input-box">
                        <?php $telephone = explode("-", $this->escapeHtml($this->getAddress()->getTelephone())); ?>
                        <input type="text" name="billing[telephonecode]" value=" " title="<?php echo $this->__('Telephone') ?>" class="input-text telephonecode" id="billing:telephonecode" placeholder="<?php echo $this->__('+31') ?>" onfocus="this.placeholder = '';" onblur="this.placeholder = '<?php echo $this->__('+31') ?>';
                               "  />
                        <input type="text" name="billing[telephone]" value="<?php if(isset($telephone[1]) && !empty($telephone[1])) echo $telephone[1]; else if(isset($telephone[0]) && !empty($telephone[0])) echo $telephone[0]; ?>"  title="<?php echo $this->__('Telephone') ?>" class="input-text telephone <?php echo $this->helper('customer/address')->getAttributeValidationClass('telephone') ?>" id="billing:telephone" placeholder="<?php echo $this->__('0224 - 212 026') ?>" onfocus="this.placeholder = '';" onblur="this.placeholder = '<?php echo $this->__('0224 - 212 026') ?>';
                               "  />
                        
                    </div>
                </div>
            </li>            
            <!-- start not logged in customer -->
            <?php if (!$this->isCustomerLoggedIn()): ?>

                <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
                <?php if ($_dob->isEnabled()): ?>
                    <li>
                        <?php
                        echo $_dob->setDate($this->getQuote()->getCustomerDob())
                                ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml()
                        ?>
                    </li>
                <?php endif ?>

                <?php /*$_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
                    <?php if ($_taxvat->isEnabled()): ?>
                    <li>
                        <?php
                        echo $_taxvat->setTaxvat($this->getQuote()->getCustomerTaxvat())
                                ->setFieldIdFormat('billing:%s')->setFieldNameFormat('billing[%s]')->toHtml()
                        ?>
                    </li>
    <?php endif*/ ?>

                <li class="fields" id="register-customer-password">
                    <div class="field">
                        <label for="billing:customer_password" class="required"><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="billing[customer_password]" id="billing:customer_password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" />
                        </div>
                    </div>
                    <div class="field">
                        <label for="billing:confirm_password" class="required"><?php echo $this->__('Confirm Password') ?></label>
                        <div class="input-box">
                            <input type="password" name="billing[confirm_password]" title="<?php echo $this->__('Confirm Password') ?>" id="billing:confirm_password" class="input-text required-entry validate-cpassword" />
                        </div>
                    </div>
                </li>            
<?php endif ?>   
            <!-- end not logged in customer -->       
        </ul>
    </div>
</fieldset>
<script type="text/javascript">
    var callingCodeConfig = JSON.parse(<?php echo $this->getCallingCode(); ?>);
    var customerAddressId='<?php echo $this->getAddress()->getId();?>'
    if(customerAddressId){
        var defaultCountry = '<?php echo $this->getAddress()->getCountry();?>'; 
    }
    else{
        var defaultCountry = '<?php echo Mage::helper('core')->getDefaultCountry(); ?>'; 
    }
    for (calling in callingCodeConfig) {
        if (callingCodeConfig[calling]['alpha2Code'] == defaultCountry) {
            codeVal = callingCodeConfig[calling]['callingCodes']['0'];
            jQuery('billing:telephonecode').value = "+" + codeVal;
            jQuery('billing:country_id').value = defaultCountry;
            jQuery('shipping:telephonecode').value = "+" + codeVal;
        }
    }
    
    function displayField(val)
    {
        if (val == 'business') {
            document.getElementById('business-vat').style.display = 'block';
            document.getElementById('business-company').style.display = 'block';
            document.getElementById('business-ref').style.display = 'block';
        }
        else {
            document.getElementById('business-vat').style.display = 'none';
            document.getElementById('business-company').style.display = 'none';
            document.getElementById('business-ref').style.display = 'none';
        }
    }
    function changeCallingCode(val, prefix) {
        var codeVal;
        for (calling in callingCodeConfig) {
            if (callingCodeConfig[calling]['alpha2Code'] == val) {
                codeVal = callingCodeConfig[calling]['callingCodes']['0'];
                jQuery(prefix + ':telephonecode').value = "+" + codeVal;
            }
        }
    }


    jQuery(document).ready(function () {
        jQuery(".accnt-country-select").niceSelect();
    });

    jQuery(window).on('load', function () {
        jQuery('.country-dropdown-method').click(function () {
                if (!jQuery(this).children('.country-select-dropdown').is(':visible')) {
                    jQuery(this).children('.country-select-dropdown').show();
                }
                else {
                    jQuery(this).children('.country-select-dropdown').hide();
                }
            });
        jQuery('.country-select-dropdown ul li').click(function () {
                var currr = jQuery(this).html();
                var curid = jQuery(this).attr('id');
                jQuery('.country-dropdown-method .current').html(currr);
                jQuery('.accnt-country-select').val(curid);
                jQuery('.accnt-country-select option').removeAttr("selected");
                jQuery('.accnt-country-select option[value=' + curid + ']').attr("selected", "selected");
                jQuery('.country-select-dropdown').slideUp();
                jQuery(this).addClass('selected');
                jQuery('.country-select-dropdown ul li').not(jQuery(this)).removeClass('selected');
                changeCallingCode(curid, 'billing');
                PCNL_START_FUNCTION();
            });
            if(defaultCountry=='NL'){
                jQuery('billing:postcode_housenumber').value ='<?php echo $this->getAddress()->getStreet(2);?>';
            }
        });    
    
</script>