<?php if (Mage::getStoreConfig('socialshare/general/enabled')) : ?>
  <div class="social_buttons">
    <div id="fb-root"></div>
    <script>
    window.fbAsyncInit = function() {
        FB.init({
          appId  : <?php echo Mage::getStoreConfig('socialshare/general/fb_appid'); ?>,
          status : true,
          cookie : true,
          xfbml  : true
        });
    };
    (function() {
        var e = document.createElement('script');
        e.src = document.location.protocol + '//connect.facebook.net/en_US/all.js';
        e.async = true;
        document.getElementById('fb-root').appendChild(e);
    }());
    </script>
    <span class="facebook" style="vertical-align: text-bottom;">
      <fb:like send="true" layout="button_count" width="60" show_faces="false" expr:href='<?php echo Mage::helper('core/url')->getCurrentUrl(); ?>' />
    </span>
    <!-- Twitter -->
      <span class="twitter">
	  	<a href="http://twitter.com/share" class="twitter-share-button" data-count="horizontal" data-via="<?php echo Mage::getStoreConfig('facebooklb/general/twitter_acc'); ?>">Tweet</a>
      </span>
	  <script type="text/javascript" src="//platform.twitter.com/widgets.js"></script>    
	<!-- Google +1 -->
    <script type="text/javascript">
      (function() {
	var po = document.createElement('script'); po.type = 'text/javascript'; po.async = true;
	po.src = 'https://apis.google.com/js/plusone.js';
	var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(po, s);
      })();
    </script>
    <!-- Place this tag where you want the +1 button to render -->
	<span class="google">
	    <g:plusone size="medium"></g:plusone>
    </span>
    <div class="pinterestContainer">
			<a href="//pinterest.com/pin/create/button/?url=http://store.virtual-brick.com/socialshare-socialbar.html?utm_medium=magentoconnect&amp;utm_source=social_bar-Demo&amp;media=http://store.virtual-brick.com/media/catalog/product/cache/1/image/265x/9df78eab33525d08d6e5fb8d27136e95/s/c/screenshot_1.png&amp;description=Let your customers easily share your product on the social networks
Increase your product's exposure for no cost!
Add a Facebook, Twitter and Google+1 and Pinterest  Buttons to your product pages and give your customers a way to connect, share, and brag about their shopping." data-pin-do="buttonPin" data-pin-config="none">
				<img src="//assets.pinterest.com/images/pidgets/pin_it_button.png">
			</a>
		</div>
</div>
<?php endif; ?>
